import type { VenueCalendarSource } from "./types";

/** Official club calendars with dated nights + (usually) lineups. */
export const VENUE_CALENDAR_SOURCES: VenueCalendarSource[] = [
  {
    venueSlug: "unvrs",
    venueName: "UNVRS",
    location: "Ibiza, Spain",
    website: "https://www.unvrs.com/",
    calendarUrl: "https://www.unvrs.com/events-calendar",
    parser: "jsonld",
    seedFile: "unvrs.json",
    weight: 36,
  },
  {
    venueSlug: "hi-ibiza",
    venueName: "Hï Ibiza",
    location: "Ibiza, Spain",
    website: "https://www.hiibiza.com/",
    calendarUrl: "https://www.hiibiza.com/events-calendar",
    parser: "jsonld",
    seedFile: "hi-ibiza.json",
    weight: 36,
  },
  {
    venueSlug: "amnesia-ibiza",
    venueName: "Amnesia Ibiza",
    location: "Ibiza, Spain",
    website: "https://www.amnesia.es/",
    calendarUrl: "https://www.amnesia.es/en/calendar/ibiza/2026/all",
    parser: "amnesia",
    seedFile: "amnesia-ibiza.json",
    defaultYear: 2026,
    weight: 34,
  },
  {
    venueSlug: "savaya",
    venueName: "Savaya",
    location: "Bali",
    website: "https://www.savaya.com/",
    calendarUrl: "https://www.savaya.com/event-calendar",
    parser: "savaya",
    seedFile: "savaya.json",
    defaultYear: 2026,
    weight: 32,
  },
  {
    venueSlug: "warehouse-project",
    venueName: "The Warehouse Project",
    location: "Manchester, UK",
    website: "https://thewarehouseproject.com/",
    calendarUrl: "https://thewarehouseproject.com/calendar/",
    parser: "warehouse-project",
    seedFile: "warehouse-project.json",
    defaultYear: 2026,
    weight: 32,
  },
  {
    venueSlug: "pacha-ibiza",
    venueName: "Pacha Ibiza",
    location: "Ibiza, Spain",
    website: "https://pacha.com/",
    calendarUrl: "https://pacha.com/events",
    parser: "pacha",
    seedFile: "pacha-ibiza.json",
    weight: 34,
  },
  {
    venueSlug: "fabric",
    venueName: "fabric",
    location: "London",
    website: "https://fabriclondon.com/",
    calendarUrl: "https://fabriclondon.com/whats-on",
    parser: "fabric",
    seedFile: "fabric.json",
    weight: 30,
  },
  {
    venueSlug: "illuzion-phuket",
    venueName: "Illuzion Phuket",
    location: "Phuket",
    website: "https://www.illuzionphuket.com/",
    calendarUrl: "https://www.illuzionphuket.com/events/",
    icsUrl: "https://www.illuzionphuket.com/events/?ical=1",
    parser: "illuzion",
    seedFile: "illuzion-phuket.json",
    weight: 28,
  },
  {
    venueSlug: "bootshaus",
    venueName: "Bootshaus",
    location: "Cologne, Germany",
    website: "https://bootshaus.tv/",
    calendarUrl: "https://bootshaus.tv/events",
    parser: "bootshaus",
    seedFile: "bootshaus.json",
    defaultYear: 2026,
    weight: 28,
  },
  {
    venueSlug: "berghain",
    venueName: "Berghain",
    location: "Berlin, Germany",
    website: "https://berghain.berlin/",
    calendarUrl: "https://berghain.berlin/en/program/",
    parser: "berghain",
    seedFile: "berghain.json",
    weight: 30,
  },
];
