import type { FingerprintSeedRow } from "../fingerprint/seeds";

/**
 * Timmy Trumpet @ Freedom Stage, Tomorrowland Weekend 2, Belgium 2026-07-25
 * Official YouTube: https://youtu.be/QcvGuOhSVlc
 * https://www.1001tracklists.com/tracklist/2nfymhx9/timmy-trumpet-freedom-stage-tomorrowland-weekend-2-belgium-2026-07-25.html
 * Overlay name TL_TIMMY_TRUMPET is too generic.
 * No SoundCloud in the operator paste — do not invent an SC slug.
 * Wire: TRACKLIST_1001_BY_SOURCE_SLUG["yt-QcvGuOhSVlc"] = TL_TIMMY_TRUMPET_TML_WE2_FREEDOM_2026
 * Captured 2026-08-24 — provenance 1001tl.
 * Distinct from Bebe Rexha Freedom WE2 (yt-KCeluZt3H9o, 2026-07-24).
 */
export const TL_TIMMY_TRUMPET_TML_WE2_FREEDOM_2026: FingerprintSeedRow[] = [
  { at: "0:12", artist: "JOOP", title: "The Future (Timmy Trumpet Edit)" },
  { at: "3:00", artist: "Empire Of The Sun", title: "Walking On A Dream (Ran-D Edit)" },
  { at: "3:27", artist: "Steve Aoki & Timmy Trumpet ft. Dr Phunk", title: "Hava" },
  { at: "3:53", artist: "Hannah Laing & Marlon Hoffstadt ft. Caroline Roxy", title: "Stomp Your Feet" },
  { at: "4:23", artist: "Bountyhunter", title: "Woops (Dimitri Vegas & Junkie Kid Remix)" },
  { at: "5:11", artist: "Showtek", title: "FTS (Fuck The System) (Organ Donors Live4Pillz Remix)" },
  { at: "5:27", artist: "Showtek", title: "FTS (Fuck The System) (Sub Zero Project Rework)" },
  { at: "5:44", artist: "LMFAO ft. Lil Jon", title: "Shots (Acappella)" },
  { at: "6:00", artist: "Timmy Trumpet", title: "Ole!" },
  { at: "6:33", artist: "Dimitri Vegas & Like Mike vs. Nicky Romero", title: "Everybody Clap" },
  { at: "7:06", artist: "W&W & Timmy Trumpet & Will Sparks ft. Sequenza", title: "Tricky Tricky (Timmy Trumpet Live Edit)" },
  { at: "7:39", artist: "John Summit", title: "LIGHTS GO OUT (Salvyan Remix)" },
  { at: "8:13", artist: "John Summit", title: "LIGHTS GO OUT (Ravenscoon & Emurse Remix)" },
  { at: "8:46", artist: "Cassian", title: "Dun Dun" },
  { at: "9:37", artist: "Sgt Slick", title: "Gimme! Gimme! Gimme! (Sgt Slick Melbourne Recut)" },
  { at: "10:03", artist: "ABBA", title: "Gimme! Gimme! Gimme! (A Man After Midnight) (Adrenalize Bootleg)" },
  { at: "10:29", artist: "ABBA", title: "Gimme! Gimme! Gimme! (A Man After Midnight) (Phyric Hardstyle Bootleg)" },
  { at: "10:54", artist: "Fallon", title: "Diet Coke (Dave Summer Edit)" },
  { at: "11:43", artist: "Dimitri Vegas & Like Mike & Maddix & Da Hool ft. Kiki Solvej", title: "Meet Her At The Love Parade" },
  { at: "12:48", artist: "Timmy Trumpet & Henrique Camacho & SMVGGLERS", title: "Oh Fortuna (Carmina Burana) (VIP Mix)" },
  { at: "13:27", artist: "Henrique Camacho & Fatality", title: "Sevilla" },
  { at: "14:06", artist: "Djo", title: "End Of Beginning" },
  { at: "14:45", artist: "Faithless", title: "Insomnia (Timmy Trumpet Edit)" },
  { at: "15:23", artist: "The Who", title: "Baba O'Riley (Timmy Trumpet Remix)" },
  { at: "16:50", artist: "Robin Schulz & Timmy Trumpet & KOPPY", title: "All The Things She Said" },
  { at: "17:25", artist: "Martin Garrix & R3HAB & Skytech", title: "Voodoo" },
  { at: "18:00", artist: "MAKJ & Timmy Trumpet ft. Andrew W.K.", title: "Party Till We Die (Louie Crick Remix)" },
  { at: "18:58", artist: "Dimitri Vegas & Like Mike & Bassjackers", title: "Axel F (Luca Agnelli Remix)" },
  { at: "19:33", artist: "Pitbull ft. Lil Jon & will.i.am & Jermaine Dupri", title: "Put Ya Fuckin Hands Up (Acappella)" },
  { at: "20:08", artist: "Timmy Trumpet & Krunk! vs. Lockdown vs. Broken Minds & AniMe", title: "Al Pacino vs. Freakshow vs. Absolute Power (Timmy Trumpet Mashup)" },
  { at: "20:20", artist: "Timmy Trumpet & Krunk!", title: "Al Pacino" },
  { at: "20:32", artist: "Broken Minds & AniMe", title: "Absolute Power" },
  { at: "20:44", artist: "Lockdown", title: "Freakshow" },
  { at: "20:56", artist: "Kanine", title: "Ultralight" },
  { at: "21:08", artist: "Chardy & Kronic", title: "S.W.A.T. Team (Everybody Fucking *Beep* Jump Acappella)" },
  { at: "21:21", artist: "Dual Damage", title: "Hiding" },
  { at: "21:33", artist: "Part Time Killer", title: "Venom" },
  { at: "22:04", artist: "John Summit & LAVINIA", title: "SHADOWS" },
  { at: "22:34", artist: "Daft Punk", title: "One More Time" },
  { at: "23:05", artist: "Junkie Kid", title: "Paradox" },
  { at: "23:35", artist: "Rihanna", title: "Where Have You Been (W&W Remix)" },
  { at: "25:20", artist: "Kid Cudi ft. MGMT & Ratatat", title: "Pursuit Of Happiness (Steve Aoki Remix)" },
  { at: "25:43", artist: "Yeah Yeah Yeahs", title: "Heads Will Roll (A-Trak Remix)" },
  { at: "26:06", artist: "Dom Dolla ft. Daya", title: "Dreamin" },
  { at: "26:29", artist: "Lynyrd Skynyrd", title: "Free Bird" },
  { at: "26:52", artist: "The Bloody Beetroots ft. Steve Aoki", title: "Warp 1.9 (Creeds Remix)" },
  { at: "27:15", artist: "MAKJ", title: "Up" },
  { at: "27:47", artist: "Tiga", title: "Mind Dimension (Adam Sellouk Remix)" },
  { at: "28:18", artist: "Timmy Trumpet ft. Savage", title: "Freaks (Dimitri Vegas & Like Mike Remix)" },
  { at: "28:44", artist: "Timmy Trumpet ft. Savage", title: "Freaks (W&W Bigroom Edit)" },
  { at: "29:10", artist: "Timmy Trumpet ft. Savage", title: "Freaks (Dr Phunk Remix)" },
  { at: "29:36", artist: "Timmy Trumpet ft. Savage", title: "Freaks (Yagoz Flip)" },
  { at: "30:02", artist: "Timmy Trumpet ft. Savage", title: "Freaks (Kiqore & GOTTLOS Edit)" },
  { at: "30:28", artist: "Timmy Trumpet X Alle Farben ft. ALEXX", title: "Chase The Feeling" },
  { at: "31:45", artist: "Capital Cities", title: "Safe And Sound (Parametricz Hardstyle Bootleg)" },
  { at: "32:57", artist: "Sebastian Ingrosso & Tommy Trash vs. John Summit & Hayla vs. Hans Zimmer", title: "Reload vs. Where You Are vs. Interstellar (MashBit Mashup)" },
  { at: "33:23", artist: "Sebastian Ingrosso & Tommy Trash ft. John Martin", title: "Reload" },
  { at: "33:49", artist: "Hans Zimmer", title: "Interstellar" },
  { at: "34:15", artist: "John Summit ft. HAYLA", title: "Where You Are (Acappella)" },
  { at: "34:41", artist: "Imogen Heap", title: "Hide & Seek (Acappella)" },
  { at: "35:06", artist: "The Prodigy", title: "Breathe (Sam Laxton & Lonskii Hard Techno Mix)" },
  { at: "35:39", artist: "Fred again.. & Skepta & PlaqueBoyMax", title: "Victory Lap" },
  { at: "36:12", artist: "HUGEL & SOLTO", title: "Jamaican (Bam Bam)" },
  { at: "37:00", artist: "Luca Agnelli", title: "Tokyo Drift" },
  { at: "37:48", artist: "4444 OF A KIND", title: "4 THE RAVE" },
  { at: "38:26", artist: "Mo-Do", title: "Eins Zwei Polizei" },
  { at: "39:03", artist: "The Ramones", title: "Blitzkrieg Bop" },
  { at: "39:32", artist: "Öwnboss & Sevek", title: "Move Your Body (Hedex VIP)" },
  { at: "40:00", artist: "The Temper Trap", title: "Sweet Disposition (John Summit & Silver Panda Remix / Senergy Techno Edit)" },
  { at: "41:35", artist: "GORDO X Reinier Zonneveld X KAAZE", title: "Loco Loco X Papi (Rudeejay & Da Brozz Bootleg)" },
  { at: "42:04", artist: "GORDO & Reinier Zonneveld", title: "Loco Loco" },
  { at: "42:34", artist: "KAAZE ft. Alina Pozi", title: "Papi" },
  { at: "43:03", artist: "Dimitri Vegas & Like Mike & Marlon Hoffstadt & DJ Konik", title: "Makina Time (Darren Styles Remix)" },
  { at: "44:30", artist: "Timmy Trumpet & Bassjackers", title: "My Way" },
  { at: "46:19", artist: "Frank Sinatra", title: "My Way (Sigit Anw Remix)" },
  { at: "48:08", artist: "Warp Brothers vs. Aquagen", title: "Phatt Bass (Luca Agnelli Remix)" },
  { at: "49:10", artist: "Blasterjaxx & Timmy Trumpet", title: "Narco (Timmy Trumpet Edit)" },
  { at: "50:02", artist: "Mr. Polska & Natte Visstick & Vieze Asbak", title: "POLSKA JUMPSTYLE" },
  { at: "50:53", artist: "Dimitri Vegas & Like Mike vs. Darren Styles", title: "Better Off Alone" },
  { at: "51:31", artist: "Justin Bieber & Nicki Minaj vs. Don Omar & Lucenzo", title: "Beauty And A Beat vs. Danza Kuduro (The Saints Edit)" },
  { at: "52:09", artist: "Don Omar ft. Lucenzo", title: "Danza Kuduro" },
  { at: "52:47", artist: "Justin Bieber ft. Nicki Minaj", title: "Beauty And A Beat" },
  { at: "53:25", artist: "Timmy Trumpet ft. Oaks", title: "Not A Place" },
  { at: "54:45", artist: "Cascada", title: "Everytime We Touch (Acappella)" },
  { at: "55:12", artist: "Martin Garrix", title: "Animals (VNDETTA Flip)" },
  { at: "56:18", artist: "HUGEL & Imael Angel & Ultra Naté", title: "Movin' To The Sun" },
  { at: "56:32", artist: "Binary Squad", title: "Hold Up" },
  { at: "56:45", artist: "Martin Garrix & Third ≡ Party & Oaks vs. David Guetta & Sia", title: "Carry You vs. Titanium (Third ≡ Party Mashup)" },
  { at: "57:25", artist: "David Guetta ft. Sia", title: "Titanium (Acappella)" },
  { at: "58:05", artist: "Martin Garrix & Third ≡ Party ft. Oaks & Declan J Donovan", title: "Carry You" },
  { at: "58:45", artist: "Carnage ft. Timmy Trumpet & KSHMR", title: "Toca (KSHMR 2025 Remix)" },
  { at: "59:45", artist: "SLUGZ", title: "THE SIGNAL" },
  { at: "1:00:01", artist: "ISOxo", title: "FUCK THE SPEAKERZ UP" },
  { at: "1:00:17", artist: "RIOT", title: "Back To Back" },
  { at: "1:00:32", artist: "Edward Maya & Vika Jigulina", title: "Stereo Love" },
  { at: "1:01:12", artist: "Rihanna ft. Calvin Harris", title: "We Found Love (Acappella)" },
  { at: "1:01:52", artist: "Avicii", title: "Levels" },
  { at: "1:02:32", artist: "Mightyfools", title: "Footrocker (Get Your, Get Your Hands Up Acappella)" },
  { at: "1:03:12", artist: "Showtek", title: "We Like To Party (Dimitri Vegas & Like Mike & Bassjackers Remix)" },
  { at: "1:03:52", artist: "Dimitri Vegas & Like Mike x Timmy Trumpet x Edward Maya", title: "Feel Your Love (Dimitri Vegas Vinyl Only Remix)" },
  { at: "1:05:21", artist: "The Irrepressibles", title: "In This Shirt" },
  { at: "1:06:33", artist: "Darren Styles & TNT", title: "Hard Beat" },
  { at: "1:07:45", artist: "Mr. Polska & Natte Visstick & Vieze Asbak", title: "POLSKA JUMPSTYLE" },
  { at: "1:08:15", artist: "THISO", title: "Elevator" },
  { at: "1:08:45", artist: "Zombie Nation", title: "Kernkraft 400 (Maddix Remix)" },
  { at: "1:09:17", artist: "David Guetta & MARTEN HØRGER pres. Men Machine & Snap!", title: "PWR" },
  { at: "1:09:48", artist: "ANOTR ft. 54 Ultra", title: "Talk To You" },
  { at: "1:11:06", artist: "Swedish House Mafia ft. John Martin", title: "Don't You Worry Child" },
  { at: "1:13:02", artist: "Timmy Trumpet & Frank Walker ft. John Martin", title: "All My Life (Timmy Trumpet Live Edit)" },
  { at: "1:14:48", artist: "Dr. Dre ft. Snoop Dogg & Kurupt & Nate Dogg", title: "The Next Episode" },
  { at: "1:15:38", artist: "Dimitri Vegas & Like Mike vs. Ummet Ozcan", title: "The Hum (Timmy Trumpet Remix)" },
  { at: "1:16:28", artist: "Dimitri Vegas & Like Mike vs. Ummet Ozcan", title: "The Hum (Nico Moreno Remix)" },
  { at: "1:17:18", artist: "Adele", title: "Hello (Koven Bootleg)" },
  { at: "1:18:14", artist: "The Prodigy", title: "Voodoo People" },
  { at: "1:19:10", artist: "Timmy Trumpet & 3 Are Legend", title: "Country Roads" },
  { at: "1:22:20", artist: "Timmy Trumpet & Olivia Sebastianelli", title: "Dance Till I Die" },
  { at: "1:23:56", artist: "The Killers", title: "Mr. Brightside (Arcando DnB Remix)" },
  { at: "1:24:55", artist: "STVW & Chockablock", title: "Mr. Brightside" },
  { at: "1:25:53", artist: "Timmy Trumpet & Steve Aoki & 3rd Wall ft. Luciano Pavarotti", title: "Nessun Dorma" },
];
