/**
 * Rebuild data/crosscheck/next-captures.json for /capture-1001.
 * Usage: npx tsx scripts/build-next-captures.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import {
  buildHeldReliveWatch,
  buildNextCaptures,
} from "../src/lib/ingest/nextCaptures";
import { extractVideoId } from "../src/lib/ingest/youtube/client";
import { YOUTUBE_SETS } from "../src/lib/ingest/youtube/videos";
import { TRACKLIST_1001_BY_SOURCE_SLUG } from "../src/lib/ingest/tracklists1001/festival2026";
import { slugify } from "../src/lib/ingest/types";
import {
  buildLiveReliveWatch,
  reliveDedupeKey,
} from "../src/lib/ingest/reliveWatch";

async function main() {
  const cwd = process.cwd();
  const curatedVideoIds = new Set<string>();
  const existingKeys = new Set<string>();
  for (const s of YOUTUBE_SETS) {
    const id = extractVideoId(s.video);
    if (id) curatedVideoIds.add(id);
    const k = reliveDedupeKey(s.title || "", slugify(s.primaryArtist.name));
    if (k) existingKeys.add(k);
  }

  let live;
  try {
    live = await buildLiveReliveWatch({
      curatedVideoIds,
      mappedSlugs: new Set(Object.keys(TRACKLIST_1001_BY_SOURCE_SLUG)),
      existingKeys,
    });
  } catch (err) {
    console.warn(
      "[next-captures] Relive playlist fetch failed:",
      err instanceof Error ? err.message : err,
    );
    live = null;
  }

  const extra = live?.unwiredOfficial ?? [];
  let presets = buildNextCaptures({
    cwd,
    limit: 12,
    extra,
  });
  try {
    const { getCaptureQueue } = await import("../src/lib/captureQueue");
    const liveQueue = await getCaptureQueue(12, extra);
    if (liveQueue.presets.length) presets = liveQueue.presets;
  } catch (err) {
    console.warn(
      "[next-captures] catalog queue unavailable, using offline reports:",
      err instanceof Error ? err.message : err,
    );
  }
  const held = live ?? {
    ...buildHeldReliveWatch(),
    playlists: [],
    unwiredOfficial: [],
  };
  const outDir = join(cwd, "data/crosscheck");
  mkdirSync(outDir, { recursive: true });

  const capturePath = join(outDir, "next-captures.json");
  writeFileSync(
    capturePath,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        note: "YT-first capture assists. Regenerated by npm run build:next-captures.",
        presets,
      },
      null,
      2,
    ) + "\n",
  );

  const heldPath = join(outDir, "held-relive-watch.json");
  writeFileSync(heldPath, JSON.stringify(held, null, 2) + "\n");

  console.log(`[next-captures] wrote ${presets.length} presets → ${capturePath}`);
  for (const p of presets) {
    console.log(`  - ${p.slug}  ${p.label}  (${p.reason ?? ""})`);
  }
  console.log(`[held-relive] wrote ${held.held.length} watches → ${heldPath}`);
}

main();
