/**
 * Rebuild data/crosscheck/next-captures.json for /capture-1001.
 * Usage: npx tsx scripts/build-next-captures.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import {
  buildHeldReliveWatch,
  buildNextCaptures,
} from "../src/lib/ingest/nextCaptures";

function main() {
  const cwd = process.cwd();
  const presets = buildNextCaptures({ cwd, limit: 10 });
  const held = buildHeldReliveWatch();
  const outDir = join(cwd, "data/crosscheck");
  mkdirSync(outDir, { recursive: true });

  const capturePath = join(outDir, "next-captures.json");
  writeFileSync(
    capturePath,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        note: "YT-first capture assists. Regenerated by npm run build:next-captures.",
        presets,
      },
      null,
      2,
    ) + "\n",
  );

  const heldPath = join(outDir, "held-relive-watch.json");
  writeFileSync(heldPath, JSON.stringify(held, null, 2) + "\n");

  console.log(`[next-captures] wrote ${presets.length} presets → ${capturePath}`);
  for (const p of presets) {
    console.log(`  - ${p.slug}  ${p.label}  (${p.reason ?? ""})`);
  }
  console.log(`[held-relive] wrote ${held.held.length} watches → ${heldPath}`);
}

main();
