/**
 * Hard pins for DJ socials that name-guessing / empty IG slots get wrong.
 * Applied on every verify-urls / fast deploy via applyKnownUrlFixes.
 *
 * Keep Beatport / official site as website when there is no personal homepage.
 * Schema stores SC / YT / IG / X / website — TikTok & Facebook stay on roster.socials.
 */

import type { PrismaClient } from "@prisma/client";
import { youtubeChannelUrl } from "../social";
import { ARTIST_ROSTER } from "./roster";
import { slugify } from "./types";

export type DjSocialPin = {
  slug: string;
  name: string;
  accent: string;
  /** Null when no verified SC — do not invent handles. */
  soundcloud: string | null;
  /** Official YouTube channel when known. */
  youtube?: string | null;
  /** Null when no verified IG — do not invent handles. */
  instagram: string | null;
  twitter?: string | null;
  website: string;
  bio: string;
};

export const DJ_SOCIAL_PINS: DjSocialPin[] = [
  {
    slug: "biscits",
    name: "BISCITS",
    accent: "#ef476f",
    soundcloud: "https://soundcloud.com/biscits",
    youtube: "https://www.youtube.com/@Biscits",
    instagram: "https://www.instagram.com/itsbiscits/",
    website: "https://www.beatport.com/artist/biscits/591990",
    bio: [
      "Tech House.",
      "Management: charlie@palmartists.com",
      "Booking N/S America: bshprits@teamwass.com",
      "Booking EU/UK: Jack@unitedtalent.com",
      "Booking AUS/NZ: Stuart@posterchild.com.au",
    ].join(" "),
  },
  {
    slug: "david-guetta",
    name: "David Guetta",
    accent: "#1e90ff",
    soundcloud: "https://soundcloud.com/davidguetta",
    youtube: "https://www.youtube.com/@davidguetta",
    instagram: "https://www.instagram.com/davidguetta/",
    twitter: "https://x.com/davidguetta",
    website: "https://davidguetta.com",
    bio: "House. Official site davidguetta.com — SC davidguetta, IG/X @davidguetta.",
  },
  {
    slug: "armin-van-buuren",
    name: "Armin van Buuren",
    accent: "#00a3e0",
    soundcloud: "https://soundcloud.com/arminvanbuuren",
    youtube: "https://www.youtube.com/@arminvanbuuren",
    instagram: "https://www.instagram.com/arminvanbuuren/",
    twitter: "https://x.com/arminvanbuuren",
    website: "https://www.arminvanbuuren.com/",
    bio: "Trance. Netherlands. Official arminvanbuuren.com — YT @arminvanbuuren, IG/X/TikTok @arminvanbuuren, SC arminvanbuuren, Armada Music.",
  },
  {
    slug: "fisher",
    name: "FISHER",
    accent: "#00c2ff",
    soundcloud: "https://soundcloud.com/fish-tales",
    youtube: "https://www.youtube.com/@fisher",
    instagram: "https://www.instagram.com/followthefishtv/",
    website: "https://followthefishtv.com",
    bio: "Tech House. Official: followthefishtv.com — IG @followthefishtv, SC fish-tales, YT @fisher.",
  },
  {
    slug: "marten-horger",
    name: "Marten Horger",
    accent: "#ff7a45",
    soundcloud: "https://soundcloud.com/marten-horger",
    instagram: "https://www.instagram.com/marten_horger/",
    website: "https://www.martenhorger.com/",
    bio: "Bass House. Berlin. Official martenhorger.com — SC marten-horger, IG @marten_horger, YT @MARTENHORGER.",
  },
  {
    slug: "artbat",
    name: "ARTBAT",
    accent: "#6c63ff",
    soundcloud: "https://soundcloud.com/artbatmusic",
    instagram: "https://www.instagram.com/artbatmusic/",
    website: "https://www.beatport.com/artist/artbat/499932",
    bio: "Melodic Techno. SC artbatmusic, IG @artbatmusic, YT @ARTBAT — Beatport artist hub.",
  },
  {
    slug: "ac-slater",
    name: "AC Slater",
    accent: "#f2b33d",
    soundcloud: "https://soundcloud.com/acslater",
    instagram: "https://www.instagram.com/djacslater/",
    website: "https://www.djacslater.com/",
    bio: "Bass House. Official djacslater.com — YT @djacslater / user/djacslater, IG @djacslater, SC acslater, Beatport artist/ac-slater/52351.",
  },
  {
    slug: "solomun",
    name: "Solomun",
    accent: "#f0e6d8",
    soundcloud: "https://soundcloud.com/solomun",
    instagram: "https://www.instagram.com/solomun/",
    website: "https://solomun.org/",
    bio: 'Melodic House. Diynamic / Solomun +1. Official solomun.org — YT @SolomunOfficial, IG @solomun, SC solomun. "Nobody is not loved."',
  },
  {
    slug: "odd-mob",
    name: "Odd Mob",
    accent: "#b8f200",
    soundcloud: "https://soundcloud.com/oddmob",
    instagram: "https://www.instagram.com/odd_mob/",
    website: "https://open.spotify.com/artist/4qLwtWhlhyAoQ4S9mSrDW9",
    bio: "Tech House. Brisbane. SC oddmob, IG @odd_mob, YT @oddmob.",
  },
  {
    slug: "westend",
    name: "Westend",
    accent: "#f72585",
    soundcloud: "https://soundcloud.com/itsthewestend",
    instagram: null,
    website: "https://www.beatport.com/artist/westend/576028",
    bio: "Tech House. NYC. SC itsthewestend (not westend), YT @itsthewestend, Beatport artist/westend/576028.",
  },
  {
    slug: "sara-landry",
    name: "Sara Landry",
    accent: "#9b5de5",
    soundcloud: "https://soundcloud.com/sara-landry-dj",
    instagram: "https://www.instagram.com/saralandrydj/",
    website: "https://www.saralandry.com",
    bio: "Hard Techno / techno. Official saralandry.com — SC sara-landry-dj, IG @saralandrydj, YT @saralandry922, Beatport artist/sara-landry/663399.",
  },
  {
    slug: "lilly-palmer",
    name: "Lilly Palmer",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/lilly_palmer",
    instagram: "https://www.instagram.com/lilly_palmerdj/",
    website: "https://www.beatport.com/artist/lilly-palmer/597345",
    bio: "Techno. SC lilly_palmer, IG @lilly_palmerdj, YT @lillypalmer_dj, Beatport artist/lilly-palmer/597345.",
  },
  {
    slug: "tape-b",
    name: "Tape B",
    accent: "#ffbe0b",
    soundcloud: "https://soundcloud.com/tape-b-official",
    instagram: null,
    website: "https://linktr.ee/tapebbeats",
    bio: "Bass / breaks. SC tape-b-official, YT @tapebbeats, linktr.ee/tapebbeats.",
  },
  {
    slug: "hntr",
    name: "HNTR",
    accent: "#00f5d4",
    soundcloud: "https://soundcloud.com/hntrnet",
    instagram: "https://www.instagram.com/hntrnet/",
    twitter: "https://twitter.com/hntrnet",
    website: "https://www.hntr.net",
    bio: "Techno. Toronto. Official hntr.net — SC hntrnet, IG/X @hntrnet, YT @hntrnet, No Neon Records.",
  },
  {
    slug: "gentlemens-groove",
    name: "Gentlemen's Groove",
    accent: "#00e5ff",
    soundcloud: "https://soundcloud.com/gentlemens-groove-records",
    instagram: null,
    website: "https://www.facebook.com/Gentlemensgroove",
    bio: "Deep house mix series (EST. 2020). Hearthis gentlemensgroove-oz; SC label gentlemens-groove-records; FB Gentlemensgroove.",
  },
  {
    slug: "charlotte-de-witte",
    name: "Charlotte de Witte",
    accent: "#e0e0e0",
    soundcloud: "https://soundcloud.com/charlottedewittemusic",
    instagram: "https://www.instagram.com/charlottedewittemusic/",
    twitter: "https://twitter.com/charlottedwitte",
    website: "https://charlottedewittemusic.com",
    bio: [
      "Techno. Belgium.",
      "Harnessing a distinct brand of artistry that knows no categorical bounds,",
      "the DJ, producer and record label head has cemented herself as one of the",
      "music industry's most in-demand names at nothing short of breakneck speed.",
      "Her signature sonic approach masterfully blends genres with a visceral energy",
      "that commands attention, the ardent catalyst in her meteoric rise from",
      "Belgium's underground to global phenomenon status.",
      "Official charlottedewittemusic.com — SC/IG/FB/TikTok/YT @charlottedewittemusic,",
      "X @charlottedwitte.",
    ].join(" "),
  },
  {
    slug: "black-coffee",
    name: "Black Coffee",
    accent: "#222222",
    soundcloud: "https://soundcloud.com/realblackcoffee",
    instagram: "https://www.instagram.com/realblackcoffee/",
    twitter: "https://x.com/RealBlackCoffee",
    website: "https://music.apple.com/za/artist/black-coffee/306140760",
    bio: "Afro House. South Africa. YT @realblackcoffee — IG/FB @realblackcoffee, X @RealBlackCoffee, SC realblackcoffee, Spotify/Apple Music artist hubs.",
  },
  {
    slug: "chapter-verse",
    name: "Chapter & Verse",
    accent: "#f77f00",
    soundcloud: "https://soundcloud.com/chapterandverseofficial",
    instagram: null,
    website: "https://www.youtube.com/@chapterandversemusic",
    bio: "Tech House. UK. YT @chapterandversemusic, SC chapterandverseofficial.",
  },
  {
    slug: "walker-royce",
    name: "Walker & Royce",
    accent: "#9ef01a",
    soundcloud: "https://soundcloud.com/walker-and-royce",
    instagram: "https://www.instagram.com/walkerandroyce/",
    twitter: "https://x.com/WalkerAndRoyce",
    website: "https://www.walkerandroyce.com/",
    bio: "Tech House. NYC duo (Sam Walker & Gavin Royce). Official walkerandroyce.com — YT @WalkerAndRoyce, IG @walkerandroyce, X @WalkerAndRoyce, FB walkerroyce, SC walker-and-royce, TikTok @walkerandroyce.",
  },
  {
    slug: "vintage-culture",
    name: "Vintage Culture",
    accent: "#e85d04",
    soundcloud: "https://soundcloud.com/vintageculturemusic",
    instagram: "https://www.instagram.com/vintageculture/",
    twitter: "https://x.com/VintageCulture",
    website: "https://vintageculture.com",
    bio: "Tech House. Brazil. Official vintageculture.com — YT @VintageCulture, IG @vintageculture, X @VintageCulture, SC vintageculturemusic, TikTok @vintageculture.",
  },
  {
    slug: "bleu-clair",
    name: "Bleu Clair",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/bleuclair",
    instagram: "https://www.instagram.com/bleuclairmusic/",
    twitter: "https://x.com/bleuclair",
    website: "https://open.spotify.com/artist/7kA4sEagpoNK91I7wr9tYr",
    bio: "Tech House. Indonesia. YT @bleuclairmusic — IG/FB/TikTok @bleuclairmusic, X @bleuclair, SC bleuclair.",
  },
  {
    slug: "hot-since-82",
    name: "Hot Since 82",
    accent: "#e9c46a",
    soundcloud: "https://soundcloud.com/hotsince-82",
    instagram: null,
    twitter: "https://x.com/hotsince82",
    website: "https://hotsince82.com",
    bio: "Tech House. Leeds, UK. Official hotsince82.com — YT @HotSince82, SC hotsince-82, X/FB hotsince82, Beatport artist/hot-since-82/212422.",
  },
  {
    slug: "adam-beyer",
    name: "Adam Beyer",
    accent: "#111111",
    soundcloud: null,
    instagram: "https://www.instagram.com/realadambeyer/",
    website: "https://open.spotify.com/artist/1btv9qmIpbp7q1ixCYNdHu",
    bio: "Techno. Drumcode. YT @adambeyer — IG @realadambeyer, TikTok @adamdrumcodebeyer, Spotify artist hub.",
  },
  {
    slug: "dijon",
    name: "DIJON",
    accent: "#f4a261",
    soundcloud: null,
    instagram: "https://www.instagram.com/dijondijon_/",
    twitter: "https://x.com/dijondijon_",
    website: "https://dijondijon.com",
    bio: "US. Official dijondijon.com — YT @dijon / @DIJONDIJON, IG @dijondijon_, X @dijondijon_. Not the Paris club Djoon.",
  },
  {
    slug: "dom-dolla",
    name: "Dom Dolla",
    accent: "#ff4d6d",
    soundcloud: "https://soundcloud.com/domdolla",
    youtube: "https://www.youtube.com/@DomDolla",
    instagram: "https://www.instagram.com/domdolla/",
    twitter: "https://x.com/domdolla",
    website: "https://domdolla.com.au",
    bio: "Tech House. Melbourne. Official domdolla.com.au — YT @DomDolla, IG/TikTok @domdolla, X @domdolla, FB domdollamusic, SC domdolla.",
  },
  {
    slug: "chris-lorenzo",
    name: "Chris Lorenzo",
    accent: "#ff6b35",
    soundcloud: "https://soundcloud.com/chris-lorenzo-1",
    youtube: "https://www.youtube.com/@ChrisLorenzo",
    instagram: "https://www.instagram.com/chrislorenzo66/",
    twitter: "https://x.com/Lorenzosbeats",
    website: "https://chrislorenzo.komi.io",
    bio: "Tech House. UK. Songstats #TechHouse — YT @ChrisLorenzo, IG @chrislorenzo66, X @Lorenzosbeats, FB chrislorenzo88, SC chris-lorenzo-1, Spotify artist hub.",
  },
  {
    slug: "hannah-wants",
    name: "Hannah Wants",
    accent: "#ff4d8d",
    soundcloud: "https://soundcloud.com/hannah_wants",
    youtube: "https://www.youtube.com/@HannahWantsDJ",
    instagram: "https://www.instagram.com/hannah_wants/",
    twitter: "https://x.com/hannah_wants",
    website: "https://www.musicglue.com/hannah-wants/",
    bio: "Tech House. UK. YT @HannahWantsDJ — IG/X @hannah_wants, FB hannahwantsdj, SC hannah_wants, Spotify artist hub.",
  },
  {
    slug: "dimitri-vegas-like-mike",
    name: "Dimitri Vegas & Like Mike",
    accent: "#f7b801",
    soundcloud: "https://soundcloud.com/dimitrivegasandlikemike",
    youtube: "https://www.youtube.com/@dimitrivegasandlikemike",
    instagram: "https://www.instagram.com/dimitrivegasandlikemike/",
    website: "https://www.youtube.com/@dimitrivegasandlikemike",
    bio: "Big Room. Belgium / Tomorrowland. YT @dimitrivegasandlikemike — IG/FB/TikTok @dimitrivegasandlikemike, SC dimitrivegasandlikemike.",
  },
  {
    slug: "msendy",
    name: "Msendy",
    accent: "#2a9d8f",
    soundcloud: "https://soundcloud.com/msandi",
    instagram: null,
    website: "https://www.mixcloud.com/Msendy/",
    bio: "Deep House. Mixcloud Msendy / Deep Perspectives — SC msandi, hearthis.at/tjzqnmf7.",
  },
  // ---- DJ Mag Top 100 handle gaps (official sites / verified SC only) ----
  {
    slug: "alok",
    name: "Alok",
    accent: "#ff6b35",
    soundcloud: "https://soundcloud.com/livealok",
    youtube: "https://www.youtube.com/channel/UCQlaArsZfebRbb70iXm6usg",
    instagram: "https://www.instagram.com/alok/",
    twitter: "https://x.com/alokoficial",
    website: "https://alokmusic.com/",
    bio: "Brazilian House / EDM. Official alokmusic.com — SC livealok, YT channel UCQlaArsZfebRbb70iXm6usg, IG @alok.",
  },
  {
    slug: "afrojack",
    name: "Afrojack",
    accent: "#ffd60a",
    soundcloud: "https://soundcloud.com/afrojack",
    youtube: "https://www.youtube.com/@afrojack",
    instagram: "https://www.instagram.com/afrojack/",
    twitter: "https://x.com/djafrojack",
    website: "https://www.afrojack.com/",
    bio: "Dutch House. Official afrojack.com — SC afrojack, YT @afrojack (not @https), IG @afrojack.",
  },
  {
    slug: "anyma",
    name: "Anyma",
    accent: "#7b2cbf",
    soundcloud: "https://soundcloud.com/anyma_ofc",
    youtube: "https://www.youtube.com/@anyma_ofc",
    instagram: "https://www.instagram.com/anyma/",
    website: "https://www.anyma.com/",
    bio: "Melodic Techno. Official anyma.com — SC anyma_ofc, YT @anyma_ofc, IG @anyma.",
  },
  {
    slug: "peggy-gou",
    name: "Peggy Gou",
    accent: "#e63946",
    soundcloud: "https://soundcloud.com/peggygou",
    youtube: "https://www.youtube.com/channel/UCWd5yMFDEuSCWzTM4xuA1fg",
    instagram: null,
    website: "https://www.peggygou.com/",
    bio: "House. Official peggygou.com — SC peggygou, YT channel UCWd5yMFDEuSCWzTM4xuA1fg.",
  },
  {
    slug: "calvin-harris",
    name: "Calvin Harris",
    accent: "#ff9f1c",
    soundcloud: "https://soundcloud.com/calvinharris",
    youtube: "https://www.youtube.com/@CalvinHarris",
    instagram: null,
    website: "https://calvinharris.com/",
    bio: "Dance / EDM. Official calvinharris.com — SC calvinharris, YT @CalvinHarris.",
  },
  {
    slug: "w-w",
    name: "W&W",
    accent: "#00b4d8",
    soundcloud: "https://soundcloud.com/wandw",
    youtube: "https://www.youtube.com/@wandwmusic",
    instagram: null,
    website: "https://www.wandwmusic.com/",
    bio: "Big Room. Official wandwmusic.com — SC wandw, YT @wandwmusic.",
  },
  {
    slug: "timmy-trumpet",
    name: "Timmy Trumpet",
    accent: "#ffba08",
    soundcloud: "https://soundcloud.com/timmytrumpet",
    youtube: "https://www.youtube.com/channel/UCd61k-5ykv_4RIbQg-Mpvrg",
    instagram: null,
    website: "https://www.timmytrumpet.com/",
    bio: "Big Room / Melbourne bounce. Official timmytrumpet.com — SC timmytrumpet.",
  },
  {
    slug: "tiesto",
    name: "Tiësto",
    accent: "#00bbf9",
    soundcloud: "https://soundcloud.com/tiesto",
    youtube: "https://www.youtube.com/@tiesto",
    instagram: null,
    website: "https://www.tiesto.com/",
    bio: "Trance / Big Room. Official tiesto.com — SC tiesto, YT @tiesto.",
  },
  {
    slug: "reinier-zonneveld",
    name: "Reinier Zonneveld",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/reinier-zonneveld",
    youtube: "https://www.youtube.com/@ReinierZonneveld_FilthOnAcid",
    instagram: null,
    // Chart page — no separate personal site confirmed in this pass.
    website: "https://djmag.com/top100djs/2025/22/reinier-zonneveld",
    bio: "Techno. SC reinier-zonneveld, YT @ReinierZonneveld_FilthOnAcid.",
  },
  {
    slug: "alan-walker",
    name: "Alan Walker",
    accent: "#56cfe1",
    soundcloud: "https://soundcloud.com/alanwalker",
    youtube: "https://www.youtube.com/@Alanwalkermusic",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/24/alan-walker",
    bio: "EDM. SC alanwalker, YT @Alanwalkermusic.",
  },
  {
    slug: "jamie-jones",
    name: "Jamie Jones",
    accent: "#f72585",
    soundcloud: "https://soundcloud.com/jamie-jones",
    youtube: "https://www.youtube.com/@JamieJonesOfficial",
    instagram: null,
    website: "https://jamiejones.com/",
    bio: "Tech House. Paradise — SC jamie-jones, YT @JamieJonesOfficial.",
  },
  {
    slug: "r3hab",
    name: "R3hab",
    accent: "#ffbe0b",
    soundcloud: "https://soundcloud.com/r3hab",
    youtube: "https://www.youtube.com/@r3hab",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/28/r3hab",
    bio: "Big Room / Future House. SC r3hab, YT @r3hab.",
  },
  {
    slug: "claptone",
    name: "Claptone",
    accent: "#ffd60a",
    soundcloud: "https://soundcloud.com/claptone",
    youtube: "https://www.youtube.com/@CLAPTONEOFFICIAL",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/30/claptone",
    bio: "Deep House. The Masquerade — SC claptone, YT @CLAPTONEOFFICIAL.",
  },
  {
    slug: "skrillex",
    name: "Skrillex",
    accent: "#80ffdb",
    soundcloud: "https://soundcloud.com/skrillex",
    youtube: "https://www.youtube.com/@skrillex",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/31/skrillex",
    bio: "Bass / Dubstep. SC skrillex, YT @skrillex.",
  },
  {
    slug: "vini-vici",
    name: "Vini Vici",
    accent: "#9b5de5",
    soundcloud: "https://soundcloud.com/vinivicimusic",
    youtube: "https://www.youtube.com/@ViniViciMusic",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/32/vini-vici",
    bio: "Psytrance. SC vinivicimusic, YT @ViniViciMusic.",
  },
  {
    slug: "indira-paganotto",
    name: "Indira Paganotto",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/indirapaganotto",
    youtube: "https://www.youtube.com/@IndiraPaganotto",
    instagram: null,
    website: "https://indirapaganotto.com/",
    bio: "Hard Techno. Official indirapaganotto.com — SC indirapaganotto, YT @IndiraPaganotto.",
  },
  {
    slug: "the-martinez-brothers",
    name: "The Martinez Brothers",
    accent: "#f4a261",
    soundcloud: "https://soundcloud.com/themartinezbros",
    youtube: "https://www.youtube.com/@TheMartinezBrosTV",
    instagram: null,
    website: "https://themartinezbrothers.com/",
    bio: "House. Official themartinezbrothers.com — SC themartinezbros, YT @TheMartinezBrosTV.",
  },
  {
    slug: "zedd",
    name: "Zedd",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/zedd",
    youtube: "https://www.youtube.com/channel/UCPNokRZ9hacjIQ3IQL6HNUQ",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/44/zedd",
    bio: "Electro House. SC zedd, YT channel UCPNokRZ9hacjIQ3IQL6HNUQ.",
  },
  // Operator batch #45–#89 — only HTTP-200 handles (no invented substitutes).
  {
    slug: "bassjackers",
    name: "Bassjackers",
    accent: "#e63946",
    soundcloud: "https://soundcloud.com/bassjackers",
    youtube: "https://www.youtube.com/@Bassjackers",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/45/bassjackers",
    bio: "Big Room. SC bassjackers, YT @Bassjackers.",
  },
  {
    slug: "quintino",
    name: "Quintino",
    accent: "#ff9f1c",
    soundcloud: "https://soundcloud.com/quintino",
    youtube: "https://www.youtube.com/@Quintino",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/47/quintino",
    bio: "Big Room. SC quintino, YT @Quintino.",
  },
  {
    slug: "boris-brejcha",
    name: "Boris Brejcha",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/boris-brejcha",
    youtube: "https://www.youtube.com/channel/UCukezONa4veoJBeK9UuVZew",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/49/boris-brejcha",
    bio: "Techno. SC boris-brejcha, YT channel UCukezONa4veoJBeK9UuVZew.",
  },
  {
    slug: "hugel",
    name: "HUGEL",
    accent: "#06d6a0",
    soundcloud: "https://soundcloud.com/hugelmusic",
    youtube: "https://www.youtube.com/@HUGELBeats",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/54/hugel",
    bio: "Melodic House. SC hugelmusic, YT @HUGELBeats.",
  },
  {
    slug: "nora-en-pure",
    name: "Nora En Pure",
    accent: "#48cae4",
    soundcloud: "https://soundcloud.com/noraenpure",
    youtube: "https://www.youtube.com/@noraenpure",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/58/nora-en-pure",
    bio: "Deep House. SC noraenpure, YT @noraenpure.",
  },
  {
    slug: "atb",
    name: "ATB",
    accent: "#0077b6",
    soundcloud: null,
    youtube: "https://www.youtube.com/user/atbtv",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/59/atb",
    bio: "Trance. YT user/atbtv.",
  },
  {
    slug: "deborah-de-luca",
    name: "Deborah De Luca",
    accent: "#c9184a",
    soundcloud: "https://soundcloud.com/deborahdeluca",
    youtube: "https://www.youtube.com/@DeborahDeLucaOfficial",
    instagram: null,
    website: "https://deborahdeluca.it/",
    bio: "Techno. Official deborahdeluca.it — SC deborahdeluca, YT @DeborahDeLucaOfficial.",
  },
  {
    slug: "above-beyond",
    name: "Above & Beyond",
    accent: "#7209b7",
    soundcloud: "https://soundcloud.com/aboveandbeyond",
    youtube: "https://www.youtube.com/@aboveandbeyond",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/61/above-beyond",
    bio: "Trance. SC aboveandbeyond, YT @aboveandbeyond.",
  },
  {
    slug: "nervo",
    name: "Nervo",
    accent: "#f72585",
    soundcloud: "https://soundcloud.com/nervomusic",
    youtube: "https://www.youtube.com/@NERVO",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/63/nervo",
    bio: "Progressive House. SC nervomusic, YT @NERVO.",
  },
  {
    slug: "sub-zero-project",
    name: "Sub Zero Project",
    accent: "#3a0ca3",
    soundcloud: "https://soundcloud.com/subzeroproject",
    youtube: "https://www.youtube.com/@SubZeroProject",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/64/sub-zero-project",
    bio: "Hardstyle. SC subzeroproject, YT @SubZeroProject.",
  },
  {
    slug: "lucas-steve",
    name: "Lucas & Steve",
    accent: "#ffb703",
    soundcloud: "https://soundcloud.com/lucasandsteve",
    youtube: "https://www.youtube.com/channel/UCIAzXmeDqLu-HY9yJ5Rd4pg",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/66/lucas-steve",
    bio: "Future House. SC lucasandsteve, YT channel UCIAzXmeDqLu-HY9yJ5Rd4pg.",
  },
  {
    slug: "nico-moreno",
    name: "Nico Moreno",
    accent: "#d00000",
    soundcloud: "https://soundcloud.com/nicomoreno",
    youtube: null,
    instagram: null,
    website: "https://djmag.com/top100djs/2025/67/nico-moreno",
    bio: "Hard Techno. SC nicomoreno.",
  },
  {
    slug: "gordo",
    name: "GORDO",
    accent: "#fb8500",
    soundcloud: null,
    youtube: "https://www.youtube.com/@gordoslife",
    instagram: null,
    website: "https://www.gordomusic.com/",
    bio: "Tech House. Official gordomusic.com — YT @gordoslife.",
  },
  {
    slug: "the-chainsmokers",
    name: "The Chainsmokers",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/thechainsmokers",
    youtube: "https://www.youtube.com/@thechainsmokers",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/70/chainsmokers",
    bio: "Future Bass. SC thechainsmokers, YT @thechainsmokers.",
  },
  {
    slug: "liu",
    name: "Liu",
    accent: "#2a9d8f",
    soundcloud: "https://soundcloud.com/liulive",
    youtube: "https://www.youtube.com/@liulive",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/71/liu",
    bio: "Brazilian Bass. SC liulive, YT @liulive.",
  },
  {
    slug: "mike-williams",
    name: "Mike Williams",
    accent: "#e9c46a",
    soundcloud: "https://soundcloud.com/mikewilliams",
    youtube: "https://www.youtube.com/@mikewilliams",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/72/mike-williams",
    bio: "Future House. SC mikewilliams, YT @mikewilliams.",
  },
  {
    slug: "kaaze",
    name: "KAAZE",
    accent: "#9b5de5",
    soundcloud: "https://soundcloud.com/kaaze",
    youtube: null,
    instagram: null,
    website: "https://djmag.com/top100djs/2025/74/kaaze",
    bio: "Progressive House. SC kaaze.",
  },
  {
    slug: "burak-yeter",
    name: "Burak Yeter",
    accent: "#e76f51",
    soundcloud: "https://soundcloud.com/burakyeter",
    youtube: "https://www.youtube.com/channel/UCkCbJ6kruvug_6XOusB1rdQ",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/76/burak-yeter",
    bio: "Deep House. SC burakyeter, YT channel UCkCbJ6kruvug_6XOusB1rdQ.",
  },
  {
    slug: "le-twins",
    name: "Le Twins",
    accent: "#8338ec",
    soundcloud: null,
    youtube: "https://www.youtube.com/@LeTwins",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/78/le-twins",
    bio: "Melodic Techno. YT @LeTwins.",
  },
  {
    slug: "i-hate-models",
    name: "I Hate Models",
    accent: "#212529",
    soundcloud: "https://soundcloud.com/ihatemodels",
    youtube: "https://www.youtube.com/@ihatemodels",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/79/i-hate-models",
    bio: "Techno. SC ihatemodels, YT @ihatemodels.",
  },
  {
    slug: "marnik",
    name: "Marnik",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/marnikofficial",
    youtube: "https://www.youtube.com/@marnikofficial",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/80/marnik",
    bio: "Big Room. SC marnikofficial, YT @marnikofficial.",
  },
  {
    slug: "chris-stussy",
    name: "Chris Stussy",
    accent: "#118ab2",
    soundcloud: "https://soundcloud.com/chrisstussy",
    youtube: "https://www.youtube.com/@chrisstussy",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/81/chris-stussy",
    bio: "Tech House. SC chrisstussy, YT @chrisstussy.",
  },
  {
    slug: "deadmau5",
    name: "deadmau5",
    accent: "#00f5d4",
    soundcloud: "https://soundcloud.com/deadmau5",
    youtube: "https://www.youtube.com/@deadmau5",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/82/deadmau5",
    bio: "Progressive House. SC deadmau5, YT @deadmau5.",
  },
  {
    slug: "wukong",
    name: "WUKONG",
    accent: "#ffd60a",
    soundcloud: "https://soundcloud.com/wukongofficial",
    youtube: null,
    instagram: null,
    website: "https://djmag.com/top100djs/2025/83/wukong",
    bio: "Melodic Techno. SC wukongofficial.",
  },
  {
    slug: "fedde-le-grand",
    name: "Fedde Le Grand",
    accent: "#ef476f",
    soundcloud: "https://soundcloud.com/feddelegrand",
    youtube: "https://www.youtube.com/@FeddeLeGrand",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/84/fedde-le-grand",
    bio: "Electro House. SC feddelegrand, YT @FeddeLeGrand.",
  },
  {
    slug: "plastik-funk",
    name: "Plastik Funk",
    accent: "#06d6a0",
    soundcloud: "https://soundcloud.com/plastikfunk",
    youtube: "https://www.youtube.com/@plastikfunk",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/86/plastik-funk",
    bio: "House. SC plastikfunk, YT @plastikfunk.",
  },
  {
    slug: "dubvision",
    name: "DubVision",
    accent: "#4361ee",
    soundcloud: "https://soundcloud.com/dubvision",
    youtube: "https://www.youtube.com/@DubVision",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/87/dubvision",
    bio: "Progressive House. SC dubvision, YT @DubVision.",
  },
  {
    slug: "b-jones",
    name: "B Jones",
    accent: "#f77f00",
    soundcloud: "https://soundcloud.com/bjonesdj",
    youtube: "https://www.youtube.com/@bjonesdj",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/88/b-jones",
    bio: "Tech House. SC bjonesdj, YT @bjonesdj.",
  },
  {
    slug: "giuseppe-ottaviani",
    name: "Giuseppe Ottaviani",
    accent: "#7b2cbf",
    soundcloud: "https://soundcloud.com/GIUSEPPEOTTAVIANI",
    youtube: "https://www.youtube.com/channel/UCdY9Y8zBYz-jHIs8DDxbd4Q",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/89/giuseppe-ottaviani",
    bio: "Trance. SC GIUSEPPEOTTAVIANI, YT channel UCdY9Y8zBYz-jHIs8DDxbd4Q.",
  },
];

/** Upsert pinned social fields for curated brand DJs. Returns rows touched. */
export async function applyDjSocialPins(prisma: PrismaClient): Promise<number> {
  let n = 0;
  for (const pin of DJ_SOCIAL_PINS) {
    const existing = await prisma.dj.findUnique({ where: { slug: pin.slug } });
    const data = {
      name: pin.name,
      accent: pin.accent,
      soundcloud: pin.soundcloud ?? null,
      youtube: pin.youtube ?? null,
      instagram: pin.instagram ?? null,
      twitter: pin.twitter ?? null,
      website: pin.website,
      bio: pin.bio,
    };
    if (existing) {
      await prisma.dj.update({ where: { id: existing.id }, data });
    } else {
      await prisma.dj.create({
        data: { slug: pin.slug, ...data },
      });
    }
    n += 1;
  }
  // Fill missing YT from the artist roster (handle → https://youtube.com/@…).
  n += await applyRosterYoutube(prisma);
  return n;
}

/** Backfill Dj.youtube from ARTIST_ROSTER youtube handles when empty. */
export async function applyRosterYoutube(prisma: PrismaClient): Promise<number> {
  let n = 0;
  for (const a of ARTIST_ROSTER) {
    const url = youtubeChannelUrl(a.youtube?.handle ?? "");
    if (!url) continue;
    const slug = slugify(a.name);
    const existing = await prisma.dj.findUnique({ where: { slug } });
    if (!existing) continue;
    if (existing.youtube === url) continue;
    // Prefer roster channel over empty / stale non-channel watch URLs.
    // Also overwrite clearly broken handles (e.g. @https from bad scrapes).
    const broken =
      /youtube\.com\/@https\b/i.test(existing.youtube ?? "") ||
      /youtube\.com\/@$/i.test(existing.youtube ?? "");
    if (
      existing.youtube &&
      !broken &&
      /youtube\.com\/@/i.test(existing.youtube) &&
      existing.youtube !== url
    ) {
      continue;
    }
    await prisma.dj.update({
      where: { id: existing.id },
      data: { youtube: url },
    });
    n += 1;
  }
  return n;
}
