/**
 * Hard-pinned DJ social rows (data only — no roster / fs imports).
 * Safe to import from Next.js page queries during static export.
 */

export type DjSocialPin = {
  slug: string;
  name: string;
  accent: string;
  /** Null when no verified SC — do not invent handles. */
  soundcloud: string | null;
  /** Official YouTube channel when known. */
  youtube?: string | null;
  /** Null when no verified IG — do not invent handles. */
  instagram: string | null;
  twitter?: string | null;
  /** Official homepage. Beatport artist hubs go on `beatport`, not here. */
  website: string;
  /** Canonical https://www.beatport.com/artist/{slug}/{id} only. */
  beatport?: string | null;
  bio: string;
};

export const DJ_SOCIAL_PINS: DjSocialPin[] = [
  {
    slug: "biscits",
    name: "BISCITS",
    accent: "#ef476f",
    soundcloud: "https://soundcloud.com/biscits",
    youtube: "https://www.youtube.com/@Biscits",
    instagram: "https://www.instagram.com/itsbiscits/",
    website: "https://www.beatport.com/artist/biscits/591990",
    bio: [
      "Tech House.",
      "Management: charlie@palmartists.com",
      "Booking N/S America: bshprits@teamwass.com",
      "Booking EU/UK: Jack@unitedtalent.com",
      "Booking AUS/NZ: Stuart@posterchild.com.au",
    ].join(" "),
  },
  {
    slug: "david-guetta",
    name: "David Guetta",
    accent: "#1e90ff",
    soundcloud: "https://soundcloud.com/davidguetta",
    youtube: "https://www.youtube.com/@davidguetta",
    instagram: "https://www.instagram.com/davidguetta/",
    twitter: "https://x.com/davidguetta",
    website: "https://davidguetta.com",
    bio: "House. Official site davidguetta.com — SC davidguetta, IG/X @davidguetta.",
  },
  {
    slug: "armin-van-buuren",
    name: "Armin van Buuren",
    accent: "#00a3e0",
    soundcloud: "https://soundcloud.com/arminvanbuuren",
    youtube: "https://www.youtube.com/@arminvanbuuren",
    instagram: "https://www.instagram.com/arminvanbuuren/",
    twitter: "https://x.com/arminvanbuuren",
    website: "https://www.arminvanbuuren.com/",
    bio: "Trance. Netherlands. Official arminvanbuuren.com — YT @arminvanbuuren, IG/X/TikTok @arminvanbuuren, SC arminvanbuuren, Armada Music.",
  },
  {
    slug: "fisher",
    name: "FISHER",
    accent: "#00c2ff",
    soundcloud: "https://soundcloud.com/fish-tales",
    youtube: "https://www.youtube.com/@fisher",
    instagram: "https://www.instagram.com/followthefishtv/",
    website: "https://followthefishtv.com",
    bio: "Tech House. Official: followthefishtv.com — IG @followthefishtv, SC fish-tales, YT @fisher.",
  },
  {
    slug: "marten-horger",
    name: "Marten Horger",
    accent: "#ff7a45",
    soundcloud: "https://soundcloud.com/marten-horger",
    instagram: "https://www.instagram.com/marten_horger/",
    website: "https://www.martenhorger.com/",
    bio: "Bass House. Berlin. Official martenhorger.com — SC marten-horger, IG @marten_horger, YT @MARTENHORGER.",
  },
  {
    slug: "artbat",
    name: "ARTBAT",
    accent: "#6c63ff",
    soundcloud: "https://soundcloud.com/artbatmusic",
    instagram: "https://www.instagram.com/artbatmusic/",
    website: "https://www.beatport.com/artist/artbat/499932",
    bio: "Melodic Techno. SC artbatmusic, IG @artbatmusic, YT @ARTBAT — Beatport artist hub.",
  },
  {
    slug: "ac-slater",
    name: "AC Slater",
    accent: "#f2b33d",
    soundcloud: "https://soundcloud.com/acslater",
    youtube: "https://www.youtube.com/@djacslater",
    instagram: "https://www.instagram.com/djacslater/",
    twitter: "https://x.com/djacslater",
    website: "https://www.djacslater.com/",
    bio: "Bass House. Official djacslater.com — YT @djacslater / user/djacslater, IG @djacslater, X @djacslater, SC acslater, Beatport artist/ac-slater/52351.",
  },
  {
    slug: "solomun",
    name: "Solomun",
    accent: "#f0e6d8",
    soundcloud: "https://soundcloud.com/solomun",
    instagram: "https://www.instagram.com/solomun/",
    website: "https://solomun.org/",
    bio: 'Melodic House. Diynamic / Solomun +1. Official solomun.org — YT @SolomunOfficial, IG @solomun, SC solomun. "Nobody is not loved."',
  },
  {
    slug: "odd-mob",
    name: "Odd Mob",
    accent: "#b8f200",
    soundcloud: "https://soundcloud.com/oddmob",
    instagram: "https://www.instagram.com/odd_mob/",
    website: "https://open.spotify.com/artist/4qLwtWhlhyAoQ4S9mSrDW9",
    bio: "Tech House. Brisbane. SC oddmob, IG @odd_mob, YT @oddmob.",
  },
  {
    slug: "westend",
    name: "Westend",
    accent: "#f72585",
    soundcloud: "https://soundcloud.com/itsthewestend",
    instagram: null,
    website: "https://www.beatport.com/artist/westend/576028",
    bio: "Tech House. NYC. SC itsthewestend (not westend), YT @itsthewestend, Beatport artist/westend/576028.",
  },
  {
    slug: "sara-landry",
    name: "Sara Landry",
    accent: "#9b5de5",
    soundcloud: "https://soundcloud.com/sara-landry-dj",
    instagram: "https://www.instagram.com/saralandrydj/",
    website: "https://www.saralandry.com",
    bio: "Hard Techno / techno. Official saralandry.com — SC sara-landry-dj, IG @saralandrydj, YT @saralandry922, Beatport artist/sara-landry/663399.",
  },
  {
    slug: "lilly-palmer",
    name: "Lilly Palmer",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/lilly_palmer",
    instagram: "https://www.instagram.com/lilly_palmerdj/",
    website: "https://www.beatport.com/artist/lilly-palmer/597345",
    bio: "Techno. SC lilly_palmer, IG @lilly_palmerdj, YT @lillypalmer_dj, Beatport artist/lilly-palmer/597345.",
  },
  {
    slug: "tape-b",
    name: "Tape B",
    accent: "#ffbe0b",
    soundcloud: "https://soundcloud.com/tape-b-official",
    instagram: null,
    website: "https://linktr.ee/tapebbeats",
    bio: "Bass / breaks. SC tape-b-official, YT @tapebbeats, linktr.ee/tapebbeats.",
  },
  {
    slug: "hntr",
    name: "HNTR",
    accent: "#00f5d4",
    soundcloud: "https://soundcloud.com/hntrnet",
    instagram: "https://www.instagram.com/hntrnet/",
    twitter: "https://twitter.com/hntrnet",
    website: "https://www.hntr.net",
    bio: "Techno. Toronto. Official hntr.net — SC hntrnet, IG/X @hntrnet, YT @hntrnet, No Neon Records.",
  },
  {
    slug: "gentlemens-groove",
    name: "Gentlemen's Groove",
    accent: "#00e5ff",
    soundcloud: "https://soundcloud.com/gentlemens-groove-records",
    instagram: null,
    website: "https://www.facebook.com/Gentlemensgroove",
    bio: "Deep house mix series (EST. 2020). Hearthis gentlemensgroove-oz; SC label gentlemens-groove-records; FB Gentlemensgroove.",
  },
  {
    slug: "charlotte-de-witte",
    name: "Charlotte de Witte",
    accent: "#e0e0e0",
    soundcloud: "https://soundcloud.com/charlottedewittemusic",
    instagram: "https://www.instagram.com/charlottedewittemusic/",
    twitter: "https://twitter.com/charlottedwitte",
    website: "https://charlottedewittemusic.com",
    bio: [
      "Techno. Belgium.",
      "Harnessing a distinct brand of artistry that knows no categorical bounds,",
      "the DJ, producer and record label head has cemented herself as one of the",
      "music industry's most in-demand names at nothing short of breakneck speed.",
      "Her signature sonic approach masterfully blends genres with a visceral energy",
      "that commands attention, the ardent catalyst in her meteoric rise from",
      "Belgium's underground to global phenomenon status.",
      "Official charlottedewittemusic.com — SC/IG/FB/TikTok/YT @charlottedewittemusic,",
      "X @charlottedwitte.",
    ].join(" "),
  },
  {
    slug: "black-coffee",
    name: "Black Coffee",
    accent: "#222222",
    soundcloud: "https://soundcloud.com/realblackcoffee",
    instagram: "https://www.instagram.com/realblackcoffee/",
    twitter: "https://x.com/RealBlackCoffee",
    website: "https://music.apple.com/za/artist/black-coffee/306140760",
    bio: "Afro House. South Africa. YT @realblackcoffee — IG/FB @realblackcoffee, X @RealBlackCoffee, SC realblackcoffee, Spotify/Apple Music artist hubs.",
  },
  {
    slug: "chapter-verse",
    name: "Chapter & Verse",
    accent: "#f77f00",
    soundcloud: "https://soundcloud.com/chapterandverseofficial",
    instagram: null,
    website: "https://www.youtube.com/@chapterandversemusic",
    bio: "Tech House. UK. YT @chapterandversemusic, SC chapterandverseofficial.",
  },
  {
    slug: "walker-royce",
    name: "Walker & Royce",
    accent: "#9ef01a",
    soundcloud: "https://soundcloud.com/walker-and-royce",
    instagram: "https://www.instagram.com/walkerandroyce/",
    twitter: "https://x.com/WalkerAndRoyce",
    website: "https://www.walkerandroyce.com/",
    bio: "Tech House. NYC duo (Sam Walker & Gavin Royce). Official walkerandroyce.com — YT @WalkerAndRoyce, IG @walkerandroyce, X @WalkerAndRoyce, FB walkerroyce, SC walker-and-royce, TikTok @walkerandroyce.",
  },
  {
    slug: "vintage-culture",
    name: "Vintage Culture",
    accent: "#e85d04",
    soundcloud: "https://soundcloud.com/vintageculturemusic",
    instagram: "https://www.instagram.com/vintageculture/",
    twitter: "https://x.com/VintageCulture",
    website: "https://vintageculture.com",
    bio: "Tech House. Brazil. Official vintageculture.com — YT @VintageCulture, IG @vintageculture, X @VintageCulture, SC vintageculturemusic, TikTok @vintageculture.",
  },
  {
    slug: "bleu-clair",
    name: "Bleu Clair",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/bleuclair",
    instagram: "https://www.instagram.com/bleuclairmusic/",
    twitter: "https://x.com/bleuclair",
    website: "https://open.spotify.com/artist/7kA4sEagpoNK91I7wr9tYr",
    bio: "Tech House. Indonesia. YT @bleuclairmusic — IG/FB/TikTok @bleuclairmusic, X @bleuclair, SC bleuclair.",
  },
  {
    slug: "hot-since-82",
    name: "Hot Since 82",
    accent: "#e9c46a",
    soundcloud: "https://soundcloud.com/hotsince-82",
    instagram: null,
    twitter: "https://x.com/hotsince82",
    website: "https://hotsince82.com",
    bio: "Tech House. Leeds, UK. Official hotsince82.com — YT @HotSince82, SC hotsince-82, X/FB hotsince82, Beatport artist/hot-since-82/212422.",
  },
  {
    slug: "adam-beyer",
    name: "Adam Beyer",
    accent: "#111111",
    soundcloud: null,
    instagram: "https://www.instagram.com/realadambeyer/",
    website: "https://open.spotify.com/artist/1btv9qmIpbp7q1ixCYNdHu",
    beatport: "https://www.beatport.com/artist/adam-beyer/6824",
    bio: "Techno. Drumcode. YT @adambeyer — IG @realadambeyer, TikTok @adamdrumcodebeyer, Spotify artist hub, Beatport artist/adam-beyer/6824.",
  },
  {
    slug: "bart-skils",
    name: "Bart Skils",
    accent: "#2a9d8f",
    soundcloud: "https://soundcloud.com/bart-skils",
    youtube: "https://www.youtube.com/@bartskils",
    instagram: "https://www.instagram.com/bart_skils/",
    website: "https://linktr.ee/bartskils",
    beatport: "https://www.beatport.com/artist/bart-skils/16211",
    bio: "Techno. Official linktr.ee/bartskils — SC bart-skils, YT @bartskils, IG @bart_skils, Beatport artist/bart-skils/16211.",
  },
  {
    slug: "maceo-plex",
    name: "Maceo Plex",
    accent: "#9b2226",
    soundcloud: null,
    instagram: null,
    website: "https://www.beatport.com/artist/maceo-plex/119538",
    beatport: "https://www.beatport.com/artist/maceo-plex/119538",
    bio: "Techno. Beatport artist/maceo-plex/119538. No official homepage pinned.",
  },
  {
    slug: "dijon",
    name: "DIJON",
    accent: "#f4a261",
    soundcloud: null,
    instagram: "https://www.instagram.com/dijondijon_/",
    twitter: "https://x.com/dijondijon_",
    website: "https://dijondijon.com",
    bio: "US. Official dijondijon.com — YT @dijon / @DIJONDIJON, IG @dijondijon_, X @dijondijon_. Not the Paris club Djoon.",
  },
  {
    slug: "dom-dolla",
    name: "Dom Dolla",
    accent: "#ff4d6d",
    soundcloud: "https://soundcloud.com/domdolla",
    youtube: "https://www.youtube.com/@DomDolla",
    instagram: "https://www.instagram.com/domdolla/",
    twitter: "https://x.com/domdolla",
    website: "https://domdolla.com.au",
    bio: "Tech House. Melbourne. Official domdolla.com.au — YT @DomDolla, IG/TikTok @domdolla, X @domdolla, FB domdollamusic, SC domdolla.",
  },
  {
    slug: "chris-lorenzo",
    name: "Chris Lorenzo",
    accent: "#ff6b35",
    soundcloud: "https://soundcloud.com/chris-lorenzo-1",
    youtube: "https://www.youtube.com/@ChrisLorenzo",
    instagram: "https://www.instagram.com/chrislorenzo66/",
    twitter: "https://x.com/Lorenzosbeats",
    website: "https://chrislorenzo.komi.io",
    bio: "Tech House. UK. Songstats #TechHouse — YT @ChrisLorenzo, IG @chrislorenzo66, X @Lorenzosbeats, FB chrislorenzo88, SC chris-lorenzo-1, Spotify artist hub.",
  },
  {
    slug: "hannah-wants",
    name: "Hannah Wants",
    accent: "#ff4d8d",
    soundcloud: "https://soundcloud.com/hannah_wants",
    youtube: "https://www.youtube.com/@HannahWantsDJ",
    instagram: "https://www.instagram.com/hannah_wants/",
    twitter: "https://x.com/hannah_wants",
    website: "https://www.musicglue.com/hannah-wants/",
    bio: "Tech House. UK. YT @HannahWantsDJ — IG/X @hannah_wants, FB hannahwantsdj, SC hannah_wants, Spotify artist hub.",
  },
  {
    slug: "dimitri-vegas-like-mike",
    name: "Dimitri Vegas & Like Mike",
    accent: "#f7b801",
    soundcloud: "https://soundcloud.com/dimitrivegasandlikemike",
    youtube: "https://www.youtube.com/@dimitrivegasandlikemike",
    instagram: "https://www.instagram.com/dimitrivegasandlikemike/",
    website: "https://www.youtube.com/@dimitrivegasandlikemike",
    bio: "Big Room. Belgium / Tomorrowland. YT @dimitrivegasandlikemike — IG/FB/TikTok @dimitrivegasandlikemike, SC dimitrivegasandlikemike.",
  },
  {
    slug: "msendy",
    name: "Msendy",
    accent: "#2a9d8f",
    soundcloud: "https://soundcloud.com/msandi",
    instagram: null,
    website: "https://www.mixcloud.com/Msendy/",
    bio: "Deep House. Mixcloud Msendy / Deep Perspectives — SC msandi, hearthis.at/tjzqnmf7.",
  },
  // ---- DJ Mag Top 100 handle gaps (official sites / YT About / verified SC) ----
  {
    slug: "alok",
    name: "Alok",
    accent: "#ff6b35",
    soundcloud: "https://soundcloud.com/livealok",
    youtube: "https://www.youtube.com/channel/UCQlaArsZfebRbb70iXm6usg",
    instagram: "https://www.instagram.com/alok/",
    twitter: "https://x.com/alokoficial",
    website: "https://alokmusic.com/",
    bio: "Brazilian House / EDM. Official alokmusic.com — SC livealok, YT channel UCQlaArsZfebRbb70iXm6usg, IG @alok.",
  },
  {
    slug: "afrojack",
    name: "Afrojack",
    accent: "#ffd60a",
    soundcloud: "https://soundcloud.com/afrojack",
    youtube: "https://www.youtube.com/@afrojack",
    instagram: "https://www.instagram.com/afrojack/",
    twitter: "https://x.com/djafrojack",
    website: "https://www.afrojack.com/",
    bio: "Dutch House. Official afrojack.com — SC afrojack, YT @afrojack (not @https), IG @afrojack.",
  },
  {
    slug: "anyma",
    name: "Anyma",
    accent: "#7b2cbf",
    soundcloud: "https://soundcloud.com/anyma_ofc",
    youtube: "https://www.youtube.com/@anyma_ofc",
    instagram: "https://www.instagram.com/anyma/",
    website: "https://www.anyma.com/",
    bio: "Melodic Techno. Official anyma.com — SC anyma_ofc, YT @anyma_ofc, IG @anyma.",
  },
  {
    slug: "peggy-gou",
    name: "Peggy Gou",
    accent: "#e63946",
    soundcloud: "https://soundcloud.com/peggygou",
    youtube: "https://www.youtube.com/channel/UCWd5yMFDEuSCWzTM4xuA1fg",
    instagram: "https://www.instagram.com/peggygou_/",
    website: "https://www.peggygou.com/",
    bio: "House. Official peggygou.com — SC peggygou, YT channel UCWd5yMFDEuSCWzTM4xuA1fg, IG @peggygou_.",
  },
  {
    slug: "calvin-harris",
    name: "Calvin Harris",
    accent: "#ff9f1c",
    soundcloud: "https://soundcloud.com/calvinharris",
    youtube: "https://www.youtube.com/@CalvinHarris",
    instagram: "https://www.instagram.com/calvinharris/",
    twitter: "https://x.com/calvinharris",
    website: "https://calvinharris.com/",
    bio: "Dance / EDM. Official calvinharris.com — SC calvinharris, YT @CalvinHarris, IG @calvinharris.",
  },
  {
    slug: "w-w",
    name: "W&W",
    accent: "#00b4d8",
    soundcloud: "https://soundcloud.com/wandw",
    youtube: "https://www.youtube.com/@wandwmusic",
    instagram: "https://www.instagram.com/wandwmusic/",
    twitter: "https://x.com/wandwmusic",
    website: "https://www.wandwmusic.com/",
    bio: "Big Room. Official wandwmusic.com — SC wandw, YT/IG @wandwmusic.",
  },
  {
    slug: "timmy-trumpet",
    name: "Timmy Trumpet",
    accent: "#ffba08",
    soundcloud: "https://soundcloud.com/timmytrumpet",
    youtube: "https://www.youtube.com/channel/UCd61k-5ykv_4RIbQg-Mpvrg",
    instagram: "https://www.instagram.com/timmytrumpet/",
    twitter: "https://x.com/timmytrumpet",
    website: "https://www.timmytrumpet.com/",
    bio: "Big Room / Melbourne bounce. Official timmytrumpet.com — SC timmytrumpet, IG @timmytrumpet.",
  },
  {
    slug: "tiesto",
    name: "Tiësto",
    accent: "#00bbf9",
    soundcloud: "https://soundcloud.com/tiesto",
    youtube: "https://www.youtube.com/@tiesto",
    instagram: "https://www.instagram.com/tiesto/",
    twitter: "https://x.com/tiesto",
    website: "https://www.tiesto.com/",
    bio: "Trance / Big Room. Official tiesto.com — SC tiesto, YT/IG @tiesto.",
  },
  {
    slug: "reinier-zonneveld",
    name: "Reinier Zonneveld",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/reinier-zonneveld",
    youtube: "https://www.youtube.com/@ReinierZonneveld_FilthOnAcid",
    instagram: "https://www.instagram.com/reinierzonneveld/",
    // Chart page — no separate personal site confirmed in this pass.
    website: "https://djmag.com/top100djs/2025/22/reinier-zonneveld",
    bio: "Techno. SC reinier-zonneveld, YT @ReinierZonneveld_FilthOnAcid, IG @reinierzonneveld.",
  },
  {
    slug: "alan-walker",
    name: "Alan Walker",
    accent: "#56cfe1",
    soundcloud: "https://soundcloud.com/alanwalker",
    youtube: "https://www.youtube.com/@Alanwalkermusic",
    instagram: "https://www.instagram.com/alanwalkermusic/",
    twitter: "https://x.com/iamalanwalker",
    website: "https://alanwalker.com/",
    bio: "EDM. SC alanwalker, YT @Alanwalkermusic, IG @alanwalkermusic.",
  },
  {
    slug: "jamie-jones",
    name: "Jamie Jones",
    accent: "#f72585",
    soundcloud: "https://soundcloud.com/jamie-jones",
    youtube: "https://www.youtube.com/@JamieJonesOfficial",
    instagram: "https://www.instagram.com/jamiejonesmusic/",
    twitter: "https://x.com/jamiejonesmusic",
    website: "https://jamiejones.com/",
    bio: "Tech House. Paradise — SC jamie-jones, YT @JamieJonesOfficial, IG @jamiejonesmusic.",
  },
  {
    slug: "r3hab",
    name: "R3hab",
    accent: "#ffbe0b",
    soundcloud: "https://soundcloud.com/r3hab",
    youtube: "https://www.youtube.com/@r3hab",
    instagram: "https://www.instagram.com/r3hab/",
    website: "https://www.r3hab.com/",
    bio: "Big Room / Future House. Official r3hab.com — SC r3hab, YT/IG @r3hab.",
  },
  {
    slug: "claptone",
    name: "Claptone",
    accent: "#ffd60a",
    soundcloud: "https://soundcloud.com/claptone",
    youtube: "https://www.youtube.com/@CLAPTONEOFFICIAL",
    instagram: "https://www.instagram.com/claptone.official/",
    twitter: "https://x.com/claptone_",
    website: "https://claptone.com/",
    bio: "Deep House. The Masquerade — SC claptone, YT @CLAPTONEOFFICIAL, IG @claptone.official.",
  },
  {
    slug: "skrillex",
    name: "Skrillex",
    accent: "#80ffdb",
    soundcloud: "https://soundcloud.com/skrillex",
    youtube: "https://www.youtube.com/@skrillex",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/31/skrillex",
    bio: "Bass / Dubstep. SC skrillex, YT @skrillex.",
  },
  {
    slug: "vini-vici",
    name: "Vini Vici",
    accent: "#9b5de5",
    soundcloud: "https://soundcloud.com/vinivicimusic",
    youtube: "https://www.youtube.com/@ViniViciMusic",
    instagram: "https://www.instagram.com/vinivicimusic/",
    twitter: "https://x.com/vinivicimusic",
    website: "https://djmag.com/top100djs/2025/32/vini-vici",
    bio: "Psytrance. SC vinivicimusic, YT @ViniViciMusic, IG @vinivicimusic.",
  },
  {
    slug: "indira-paganotto",
    name: "Indira Paganotto",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/indirapaganotto",
    youtube: "https://www.youtube.com/@IndiraPaganotto",
    instagram: null,
    website: "https://indirapaganotto.com/",
    bio: "Hard Techno. Official indirapaganotto.com — SC indirapaganotto, YT @IndiraPaganotto.",
  },
  {
    slug: "the-martinez-brothers",
    name: "The Martinez Brothers",
    accent: "#f4a261",
    soundcloud: "https://soundcloud.com/themartinezbros",
    youtube: "https://www.youtube.com/@TheMartinezBrosTV",
    instagram: "https://www.instagram.com/themartinezbros/",
    website: "https://themartinezbrothers.com/",
    bio: "House. Official themartinezbrothers.com — SC themartinezbros, YT @TheMartinezBrosTV, IG @themartinezbros.",
  },
  {
    slug: "zedd",
    name: "Zedd",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/zedd",
    youtube: "https://www.youtube.com/channel/UCPNokRZ9hacjIQ3IQL6HNUQ",
    instagram: "https://www.instagram.com/zedd/",
    twitter: "https://x.com/zedd",
    website: "https://www.zedd.net/",
    bio: "Electro House. SC zedd, YT channel UCPNokRZ9hacjIQ3IQL6HNUQ, IG @zedd.",
  },
  // Operator batch #45–#89 — only HTTP-200 handles (no invented substitutes).
  {
    slug: "bassjackers",
    name: "Bassjackers",
    accent: "#e63946",
    soundcloud: "https://soundcloud.com/bassjackers",
    youtube: "https://www.youtube.com/@Bassjackers",
    instagram: "https://www.instagram.com/bassjackers/",
    website: "https://www.bassjackers.com/",
    bio: "Big Room. SC bassjackers, YT @Bassjackers, IG @bassjackers.",
  },
  {
    slug: "quintino",
    name: "Quintino",
    accent: "#ff9f1c",
    soundcloud: "https://soundcloud.com/quintino",
    youtube: "https://www.youtube.com/@Quintino",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/47/quintino",
    bio: "Big Room. SC quintino, YT @Quintino.",
  },
  {
    slug: "boris-brejcha",
    name: "Boris Brejcha",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/boris-brejcha",
    youtube: "https://www.youtube.com/channel/UCukezONa4veoJBeK9UuVZew",
    instagram: "https://www.instagram.com/borisbrejcha/",
    twitter: "https://x.com/bb_borisbrejcha",
    website: "https://www.borisbrejcha.de/",
    bio: "Techno. SC boris-brejcha, YT channel UCukezONa4veoJBeK9UuVZew, IG @borisbrejcha.",
  },
  {
    slug: "hugel",
    name: "HUGEL",
    accent: "#06d6a0",
    soundcloud: "https://soundcloud.com/hugelmusic",
    youtube: "https://www.youtube.com/@HUGELBeats",
    instagram: "https://www.instagram.com/hugelthug/",
    website: "https://www.djhugel.com/",
    bio: "Melodic House. SC hugelmusic, YT @HUGELBeats, IG @hugelthug.",
  },
  {
    slug: "nora-en-pure",
    name: "Nora En Pure",
    accent: "#48cae4",
    soundcloud: "https://soundcloud.com/noraenpure",
    youtube: "https://www.youtube.com/@noraenpure",
    instagram: "https://www.instagram.com/noraenpure/",
    website: "https://www.noraenpure.com/",
    bio: "Deep House. Official noraenpure.com — SC noraenpure, YT/IG @noraenpure.",
  },
  {
    slug: "atb",
    name: "ATB",
    accent: "#0077b6",
    soundcloud: "https://soundcloud.com/atb-music",
    youtube: "https://www.youtube.com/@atb",
    instagram: "https://instagram.com/atbandre",
    twitter: "https://twitter.com/atbandre",
    website: "https://atb-music.com",
    bio: "Trance. Official atb-music.com — SC atb-music, YT @atb, IG/X @atbandre.",
  },
  {
    slug: "deborah-de-luca",
    name: "Deborah De Luca",
    accent: "#c9184a",
    soundcloud: "https://soundcloud.com/deborahdeluca",
    youtube: "https://www.youtube.com/@DeborahDeLucaOfficial",
    instagram: null,
    website: "https://deborahdeluca.it/",
    bio: "Techno. Official deborahdeluca.it — SC deborahdeluca, YT @DeborahDeLucaOfficial.",
  },
  {
    slug: "above-beyond",
    name: "Above & Beyond",
    accent: "#7209b7",
    soundcloud: "https://soundcloud.com/aboveandbeyond",
    youtube: "https://www.youtube.com/@aboveandbeyond",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/61/above-beyond",
    bio: "Trance. SC aboveandbeyond, YT @aboveandbeyond.",
  },
  {
    slug: "nervo",
    name: "Nervo",
    accent: "#f72585",
    soundcloud: "https://soundcloud.com/nervomusic",
    youtube: "https://www.youtube.com/@NERVO",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/63/nervo",
    bio: "Progressive House. SC nervomusic, YT @NERVO.",
  },
  {
    slug: "sub-zero-project",
    name: "Sub Zero Project",
    accent: "#3a0ca3",
    soundcloud: "https://soundcloud.com/subzeroproject",
    youtube: "https://www.youtube.com/@SubZeroProject",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/64/sub-zero-project",
    bio: "Hardstyle. SC subzeroproject, YT @SubZeroProject.",
  },
  {
    slug: "lucas-steve",
    name: "Lucas & Steve",
    accent: "#ffb703",
    soundcloud: "https://soundcloud.com/lucasandsteve",
    youtube: "https://www.youtube.com/channel/UCIAzXmeDqLu-HY9yJ5Rd4pg",
    instagram: "https://www.instagram.com/lucasandsteve/",
    twitter: "https://x.com/lucasandsteve",
    website: "https://www.lucasandsteve.com/",
    bio: "Future House. SC lucasandsteve, YT channel UCIAzXmeDqLu-HY9yJ5Rd4pg, IG @lucasandsteve.",
  },
  {
    slug: "nico-moreno",
    name: "Nico Moreno",
    accent: "#d00000",
    // Bare nicomoreno is a different/smaller account — official is nicomorenomusic.
    soundcloud: "https://soundcloud.com/nicomorenomusic",
    youtube: "https://www.youtube.com/@nicomoreno_music",
    instagram: "https://instagram.com/nicomorenomusic",
    website: "https://nicomoreno.komi.io/",
    bio: "Hard Techno. SC nicomorenomusic (not bare nicomoreno), YT @nicomoreno_music, IG @nicomorenomusic.",
  },
  {
    slug: "gordo",
    name: "GORDO",
    accent: "#fb8500",
    soundcloud: "https://soundcloud.com/gordoszn",
    youtube: "https://www.youtube.com/@gordoszn",
    instagram: "https://instagram.com/gordoszn",
    twitter: "https://twitter.com/gordoszn",
    website: "https://www.gordoszn.com/",
    bio: "Tech House. Official gordoszn.com — SC/YT/IG/X @gordoszn (not @gordoslife).",
  },
  {
    slug: "the-chainsmokers",
    name: "The Chainsmokers",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/thechainsmokers",
    youtube: "https://www.youtube.com/@thechainsmokers",
    instagram: "https://www.instagram.com/thechainsmokers/",
    twitter: "https://x.com/thechainsmokers",
    website: "https://thechainsmokers.com/",
    bio: "Future Bass. Official thechainsmokers.com — SC thechainsmokers, YT/IG @thechainsmokers.",
  },
  {
    slug: "liu",
    name: "Liu",
    accent: "#2a9d8f",
    soundcloud: "https://soundcloud.com/liulive",
    youtube: "https://www.youtube.com/@Liumusic",
    instagram: "https://www.instagram.com/liulive/",
    twitter: "https://twitter.com/liulive",
    website: "https://djmag.com/top100djs/2025/71/liu",
    bio: "Brazilian Bass. Brazil. Official YT @Liumusic — SC/IG/X liulive. Do not use YT @liulive (different channel).",
  },
  {
    slug: "mike-williams",
    name: "Mike Williams",
    accent: "#e9c46a",
    soundcloud: "https://soundcloud.com/mikewilliams",
    youtube: "https://www.youtube.com/@mikewilliams",
    instagram: "https://www.instagram.com/mikewilliams/",
    website: "https://djmag.com/top100djs/2025/72/mike-williams",
    bio: "Future House. SC mikewilliams, YT/IG @mikewilliams.",
  },
  {
    slug: "kaaze",
    name: "KAAZE",
    accent: "#9b5de5",
    soundcloud: "https://soundcloud.com/kaaze",
    // @KAAZE 404 — official handle is @KAAZEOfficial (API-resolved).
    youtube: "https://www.youtube.com/@KAAZEOfficial",
    instagram: "https://www.instagram.com/iamkaaze/",
    twitter: "https://x.com/iamkaaze",
    website: "https://djmag.com/top100djs/2025/74/kaaze",
    bio: "Progressive House. SC kaaze, YT @KAAZEOfficial (not bare @KAAZE), IG @iamkaaze.",
  },
  {
    slug: "burak-yeter",
    name: "Burak Yeter",
    accent: "#e76f51",
    soundcloud: "https://soundcloud.com/burakyeter",
    youtube: "https://www.youtube.com/channel/UCkCbJ6kruvug_6XOusB1rdQ",
    instagram: "https://www.instagram.com/burakyeter/",
    website: "https://burakyeter.com/",
    bio: "Deep House. SC burakyeter, YT channel UCkCbJ6kruvug_6XOusB1rdQ, IG @burakyeter.",
  },
  {
    slug: "le-twins",
    name: "Le Twins",
    accent: "#8338ec",
    soundcloud: "https://soundcloud.com/le-twins-52553281",
    youtube: "https://www.youtube.com/@letwinsdjs",
    instagram: "https://instagram.com/officialletwins",
    twitter: "https://twitter.com/Letwinsofficial",
    website: "https://djmag.com/top100djs/2025/78/le-twins",
    bio: "Melodic Techno. SC le-twins-52553281, YT @letwinsdjs (not @LeTwins), IG @officialletwins.",
  },
  {
    slug: "i-hate-models",
    name: "I Hate Models",
    accent: "#212529",
    soundcloud: "https://soundcloud.com/ihatemodels",
    youtube: "https://www.youtube.com/@ihatemodels",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/79/i-hate-models",
    bio: "Techno. SC ihatemodels, YT @ihatemodels.",
  },
  {
    slug: "marnik",
    name: "Marnik",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/marnikofficial",
    youtube: "https://www.youtube.com/@marnikofficial",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/80/marnik",
    bio: "Big Room. SC marnikofficial, YT @marnikofficial.",
  },
  {
    slug: "chris-stussy",
    name: "Chris Stussy",
    accent: "#118ab2",
    soundcloud: "https://soundcloud.com/chrisstussy",
    youtube: "https://www.youtube.com/@chrisstussy",
    instagram: "https://www.instagram.com/chrisstussydj/",
    twitter: "https://x.com/djchrisstussy",
    website: "https://djmag.com/top100djs/2025/81/chris-stussy",
    bio: "Tech House. SC chrisstussy, YT @chrisstussy, IG @chrisstussydj.",
  },
  {
    slug: "deadmau5",
    name: "deadmau5",
    accent: "#00f5d4",
    soundcloud: "https://soundcloud.com/deadmau5",
    youtube: "https://www.youtube.com/@deadmau5",
    instagram: "https://www.instagram.com/deadmau5/",
    twitter: "https://x.com/deadmau5",
    website: "https://deadmau5.com/",
    bio: "Progressive House. Official deadmau5.com — SC deadmau5, YT/IG @deadmau5.",
  },
  {
    slug: "wukong",
    name: "WUKONG",
    accent: "#ffd60a",
    soundcloud: "https://soundcloud.com/wukongofficial",
    // @wukong / @WUKONG 404 — official handle is @WUKONGofficial (API-resolved).
    youtube: "https://www.youtube.com/@WUKONGofficial",
    instagram: "https://www.instagram.com/wukongmusic/",
    website: "https://djmag.com/top100djs/2025/83/wukong",
    bio: "Melodic Techno. SC wukongofficial, YT @WUKONGofficial (not bare @wukong), IG @wukongmusic.",
  },
  {
    slug: "fedde-le-grand",
    name: "Fedde Le Grand",
    accent: "#ef476f",
    soundcloud: "https://soundcloud.com/feddelegrand",
    youtube: "https://www.youtube.com/@FeddeLeGrand",
    instagram: "https://www.instagram.com/feddelegrand/",
    twitter: "https://x.com/feddelegrand",
    website: "https://feddelegrand.com/",
    bio: "Electro House. SC feddelegrand, YT @FeddeLeGrand, IG @feddelegrand.",
  },
  {
    slug: "plastik-funk",
    name: "Plastik Funk",
    accent: "#06d6a0",
    soundcloud: "https://soundcloud.com/plastikfunk",
    youtube: "https://www.youtube.com/@plastikfunk",
    instagram: "https://www.instagram.com/plastikfunk/",
    website: "https://djmag.com/top100djs/2025/86/plastik-funk",
    bio: "House. SC plastikfunk, YT/IG @plastikfunk.",
  },
  {
    slug: "dubvision",
    name: "DubVision",
    accent: "#4361ee",
    soundcloud: "https://soundcloud.com/dubvision",
    youtube: "https://www.youtube.com/@DubVision",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/87/dubvision",
    bio: "Progressive House. SC dubvision, YT @DubVision.",
  },
  {
    slug: "b-jones",
    name: "B Jones",
    accent: "#f77f00",
    soundcloud: "https://soundcloud.com/bjonesdj",
    youtube: "https://www.youtube.com/@bjonesdj",
    instagram: "https://www.instagram.com/bjonesdj/",
    website: "https://bjonesdj.com/",
    bio: "Tech House. Official bjonesdj.com — SC bjonesdj, YT/IG @bjonesdj.",
  },
  {
    slug: "giuseppe-ottaviani",
    name: "Giuseppe Ottaviani",
    accent: "#7b2cbf",
    soundcloud: "https://soundcloud.com/GIUSEPPEOTTAVIANI",
    youtube: "https://www.youtube.com/channel/UCdY9Y8zBYz-jHIs8DDxbd4Q",
    instagram: "https://www.instagram.com/giuseppeottaviani/",
    website: "https://www.giuseppeottaviani.com/",
    bio: "Trance. SC GIUSEPPEOTTAVIANI, YT channel UCdY9Y8zBYz-jHIs8DDxbd4Q, IG @giuseppeottaviani.",
  },
  // Handle-gap batch — profile-verified only (reject soft-404 / wrong-person pages).
  {
    slug: "kshmr",
    name: "KSHMR",
    accent: "#e63946",
    soundcloud: "https://soundcloud.com/kshmr",
    youtube: "https://www.youtube.com/channel/UCFMjkrMT7Gvg84v0av-DIwA",
    instagram: "https://www.instagram.com/kshmr/",
    twitter: "https://x.com/kshmrmusic",
    website: "https://welcometokshmr.com/",
    bio: "Big Room / Festival. SC kshmr (~403k), YT channel UCFMjkrMT7Gvg84v0av-DIwA, IG @kshmr.",
  },
  {
    slug: "nicky-romero",
    name: "Nicky Romero",
    accent: "#ffbe0b",
    soundcloud: "https://soundcloud.com/nickyromero",
    youtube: "https://www.youtube.com/user/nickyromerotv",
    instagram: "https://www.instagram.com/nickyromero/",
    twitter: "https://x.com/nickyromero",
    website: "https://nickyromero.com/",
    bio: "Progressive House. Official nickyromero.com — SC nickyromero, YT user/nickyromerotv, IG @nickyromero.",
  },
  {
    slug: "dj-snake",
    name: "DJ Snake",
    accent: "#80ffdb",
    soundcloud: "https://soundcloud.com/djsnake",
    youtube: "https://www.youtube.com/@DJSnake",
    instagram: "https://instagram.com/djsnake",
    twitter: "https://twitter.com/djsnake",
    website: "https://djsnake.com/",
    bio: "Trap / Bass. Official djsnake.com — SC djsnake (not on.soundcloud shortlink), YT @DJSnake.",
  },
  {
    slug: "michael-bibi",
    name: "Michael Bibi",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/bibi-87",
    // @MichaelBibiOfficial was a rejected invent — real handle is @michaelbibi.
    youtube: "https://www.youtube.com/@michaelbibi",
    instagram: "https://www.instagram.com/michael_bibi_/",
    twitter: "https://x.com/michaelbibi1",
    website: "https://www.michaelbibi.com/",
    bio: "Tech House. SC bibi-87, YT @michaelbibi (not @MichaelBibiOfficial), IG @michael_bibi_.",
  },
  {
    slug: "alesso",
    name: "Alesso",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/alesso",
    youtube: "https://www.youtube.com/@alesso",
    instagram: "https://www.instagram.com/alesso/",
    twitter: "https://x.com/alesso",
    website: "https://alessoworld.com/",
    bio: "Progressive House. Official alessoworld.com — SC alesso (~743k), YT/IG @alesso (~2.6M).",
  },
  {
    slug: "mochakk",
    name: "Mochakk",
    accent: "#f4a261",
    // Bare /mochakk is a 1-follower stub — real profile is mochakkmusic (Pedro Maia).
    soundcloud: "https://soundcloud.com/mochakkmusic",
    youtube: "https://www.youtube.com/@mochakk",
    instagram: "https://www.instagram.com/mochakk/",
    website: "https://mochakk.com/",
    bio: "Tech House. Official mochakk.com — SC mochakkmusic (not bare mochakk), YT/IG @mochakk.",
  },
  {
    slug: "cuebrick",
    name: "Cuebrick",
    accent: "#8338ec",
    soundcloud: "https://soundcloud.com/cuebrick",
    youtube: "https://www.youtube.com/@cuebrick",
    instagram: "https://www.instagram.com/cuebrick_dj/",
    twitter: "https://x.com/cuebrick_dj",
    website: "https://djmag.com/top100djs/2025/90/cuebrick",
    bio: "Big Room. SC cuebrick (~20k), YT @cuebrick, IG @cuebrick_dj.",
  },
  {
    slug: "mariana-bo",
    name: "Mariana Bo",
    accent: "#e63946",
    soundcloud: "https://soundcloud.com/borrego-s",
    youtube: "https://www.youtube.com/@marianabo",
    instagram: "https://www.threads.com/@djmarianabo",
    website: "https://djmag.com/top100djs/2025/91/mariana-bo",
    bio: "Hardstyle. SC borrego-s (MARIANA BO Official), YT @marianabo, Threads @djmarianabo.",
  },
  {
    slug: "fantasm",
    name: "Fantasm",
    accent: "#d00000",
    // Bare @fantasm is a cyber-security channel — real DJ is @fantasm_techno.
    soundcloud: "https://soundcloud.com/kenzo-meservey",
    youtube: "https://www.youtube.com/@fantasm_techno",
    instagram: "https://www.instagram.com/fantasm_techno/",
    website: "https://djmag.com/top100djs/2025/93/fantasm",
    bio: "Hard Techno. SC kenzo-meservey, YT/IG @fantasm_techno (not bare @fantasm).",
  },
  {
    slug: "vinai",
    name: "VINAI",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/wearevinai",
    // Bare @VINAI resolves to an empty channel — official is @vinaiofficial.
    youtube: "https://www.youtube.com/@vinaiofficial",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/94/vinai",
    bio: "Big Room. SC wearevinai, YT @vinaiofficial (not bare @VINAI).",
  },
  {
    slug: "faustix",
    name: "Faustix",
    accent: "#ffba08",
    soundcloud: "https://soundcloud.com/faustix",
    // Bare @faustix is Faust-IX — Danish Faustix is @faustixmusic.
    youtube: "https://www.youtube.com/@faustixmusic",
    instagram: "https://www.instagram.com/faustix/",
    website: "https://djmag.com/top100djs/2025/96/faustix",
    bio: "Future House. SC faustix, YT @faustixmusic (not bare @faustix), IG @faustix.",
  },
  {
    slug: "honey-dijon",
    name: "Honey Dijon",
    accent: "#f72585",
    soundcloud: "https://soundcloud.com/honeydijon",
    youtube: "https://www.youtube.com/@honeydijon",
    instagram: "https://www.instagram.com/honeydijon/",
    website: "https://djmag.com/top100djs/2025/97/honey-dijon",
    bio: "House. SC honeydijon, YT/IG @honeydijon. Not the Paris club Djoon.",
  },
  {
    slug: "nils-van-zandt",
    name: "Nils van Zandt",
    accent: "#00b4d8",
    // Bare nilsvanzandt is 0-follower stub — real is nilsvanzandtofficial.
    soundcloud: "https://soundcloud.com/nilsvanzandtofficial",
    youtube: "https://www.youtube.com/@nilsvanzandt",
    instagram: null,
    website: "https://djmag.com/top100djs/2025/98/nils-van-zandt",
    bio: "Big Room. SC nilsvanzandtofficial, YT @nilsvanzandt.",
  },
  {
    slug: "marlon-hoffstadt",
    name: "Marlon Hoffstadt",
    accent: "#ff9f1c",
    soundcloud: "https://soundcloud.com/marlonhoffstadt",
    youtube: "https://www.youtube.com/@marlonhoffstadt",
    instagram: "https://www.instagram.com/marlonhoffstadt/",
    website: "https://marlonhoffstadt.com/",
    bio: "Trance / Hard Dance (DJ Daddy Trance). Official marlonhoffstadt.com — SC marlonhoffstadt, YT/IG @marlonhoffstadt.",
  },
  {
    slug: "marshmello",
    name: "Marshmello",
    accent: "#e9ecef",
    soundcloud: "https://soundcloud.com/marshmellomusic",
    youtube: "https://www.youtube.com/channel/UCEdvpU2pFRCVqU6yIPyTpMQ",
    instagram: "https://www.instagram.com/marshmello/",
    twitter: "https://x.com/marshmello",
    website: "https://marshmellomusic.com/",
    bio: "Future Bass. SC marshmellomusic, YT channel UCEdvpU2pFRCVqU6yIPyTpMQ, IG @marshmello.",
  },
  // Verified 2026-07-31 from official YouTube About / social link blocks.
  {
    slug: "fred-again",
    name: "Fred again...",
    accent: "#adb5bd",
    soundcloud: "https://soundcloud.com/fredagain",
    youtube: "https://www.youtube.com/@Fredagainagain",
    instagram: "https://instagram.com/fredagainagainagainagainagain",
    website: "https://fredagain.lnk.to/community",
    bio: "UK. YT @Fredagainagain, SC fredagain, IG @fredagainagainagainagainagain.",
  },
  {
    slug: "swedish-house-mafia",
    name: "Swedish House Mafia",
    accent: "#212529",
    soundcloud: "https://soundcloud.com/officialswedishhousemafia",
    youtube: "https://www.youtube.com/@swedishhousemafia",
    instagram: "https://instagram.com/swedishhousemafia",
    twitter: "https://twitter.com/swedishousemfia",
    website: "https://swedishhousemafia.com",
    bio: "House. Official swedishhousemafia.com — SC officialswedishhousemafia, YT @swedishhousemafia, SUPERHUMAN label.",
  },
  {
    slug: "joel-corry",
    name: "Joel Corry",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/joelcorry",
    youtube: "https://www.youtube.com/@JoelCorry",
    instagram: "https://instagram.com/joelcorry",
    twitter: "https://twitter.com/JoelCorry",
    website: "https://joelcorry.com",
    bio: "House. Official joelcorry.com — SC joelcorry, YT @JoelCorry, IG/X @joelcorry.",
  },
  {
    // Verified 2026-07-31 from YT About — artist SC is maddixmusic (not label extaticrecords).
    slug: "maddix",
    name: "Maddix",
    accent: "#7b2cbf",
    soundcloud: "https://soundcloud.com/maddixmusic",
    youtube: "https://www.youtube.com/@maddixmusic",
    instagram: "https://instagram.com/maddixmusic",
    twitter: "https://twitter.com/MaddixMusic",
    website: "https://maddixmusic.com",
    bio: "Techno / rave. Official maddixmusic.com — SC maddixmusic (not Extatic label), YT/IG @maddixmusic, X @MaddixMusic.",
  },
  {
    // Verified 2026-07-31 from YT About — keep lo-freq-1 (lostfrequencies has 0 tracks).
    slug: "lost-frequencies",
    name: "Lost Frequencies",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/lo-freq-1",
    youtube: "https://www.youtube.com/@LostFrequencies",
    instagram: "https://instagram.com/lostfrequencies",
    twitter: "https://x.com/lfrequencies",
    website: "https://lostfrequencies.com/",
    bio: "Melodic House. Official lostfrequencies.com — SC lo-freq-1, YT @LostFrequencies, IG @lostfrequencies, X @lfrequencies.",
  },
  // Off-roster Top 100 → deep-scan batch (handles verified 2026-07-31).
  {
    slug: "john-summit",
    name: "John Summit",
    accent: "#4cc9f0",
    soundcloud: "https://soundcloud.com/johnsummit",
    youtube: "https://www.youtube.com/@johnsummit",
    instagram: "https://www.instagram.com/johnsummit/",
    twitter: "https://x.com/johnsummit",
    website: "https://www.johnsummitmusic.com/",
    bio: "Tech House. Official johnsummitmusic.com — SC johnsummit, YT @johnsummit, IG @johnsummit.",
  },
  {
    slug: "martin-garrix",
    name: "Martin Garrix",
    accent: "#ff9f1c",
    soundcloud: "https://soundcloud.com/martingarrix",
    youtube: "https://www.youtube.com/@MartinGarrix",
    instagram: "https://www.instagram.com/martingarrix/",
    twitter: "https://x.com/martingarrix",
    website: "https://martingarrix.com/",
    bio: "Big Room. Official martingarrix.com — SC martingarrix, YT @MartinGarrix, IG @martingarrix.",
  },
  {
    slug: "don-diablo",
    name: "Don Diablo",
    accent: "#ff006e",
    soundcloud: "https://soundcloud.com/dondiablo",
    youtube: "https://www.youtube.com/@DonDiablo",
    instagram: "https://www.instagram.com/dondiablo/",
    website: "https://www.dondiablo.com/",
    bio: "Future House. Official dondiablo.com — SC dondiablo, YT @DonDiablo, IG @dondiablo.",
  },
  {
    slug: "steve-aoki",
    name: "Steve Aoki",
    accent: "#3a86ff",
    soundcloud: "https://soundcloud.com/steveaoki",
    youtube: "https://www.youtube.com/@SteveAoki",
    instagram: null,
    website: "https://www.steveaoki.com/",
    bio: "Electro House. Official steveaoki.com — SC steveaoki, YT @SteveAoki.",
  },
  {
    slug: "hardwell",
    name: "Hardwell",
    accent: "#ef233c",
    soundcloud: "https://soundcloud.com/hardwell",
    youtube: "https://www.youtube.com/@hardwell",
    instagram: "https://www.instagram.com/hardwell/",
    twitter: "https://x.com/hardwell",
    website: "https://djhardwell.com/",
    bio: "Big Room. Official djhardwell.com — SC hardwell, YT/IG @hardwell.",
  },
  {
    slug: "carl-cox",
    name: "Carl Cox",
    accent: "#212529",
    soundcloud: "https://soundcloud.com/carl-cox",
    youtube: "https://www.youtube.com/@CarlCoxofficialTV",
    instagram: "https://instagram.com/carlcoxofficial",
    website: "https://www.carlcox.com/",
    bio: "Techno. Official carlcox.com — SC carl-cox, YT @CarlCoxofficialTV, IG @carlcoxofficial.",
  },
  {
    slug: "eric-prydz",
    name: "Eric Prydz",
    accent: "#7209b7",
    soundcloud: "https://soundcloud.com/eric-prydz",
    youtube: "https://www.youtube.com/@ericprydz",
    instagram: "https://www.instagram.com/ericprydz/",
    twitter: "https://x.com/ericprydz",
    website: "https://www.ericprydz.com/",
    bio: "Progressive House. Official ericprydz.com — SC eric-prydz, YT/IG @ericprydz.",
  },
  {
    slug: "amelie-lens",
    name: "Amelie Lens",
    accent: "#d00000",
    soundcloud: "https://soundcloud.com/amelielens",
    youtube: "https://www.youtube.com/@AmelieLens",
    instagram: "https://instagram.com/amelie_lens",
    twitter: "https://x.com/AmelieLENS",
    website: "https://www.amelielens.com/",
    bio: "Techno. Official amelielens.com — SC amelielens, YT @AmelieLens, IG @amelie_lens.",
  },
  {
    slug: "paul-van-dyk",
    name: "Paul van Dyk",
    accent: "#00b4d8",
    soundcloud: "https://soundcloud.com/paulvandykofficial",
    youtube: "https://www.youtube.com/@PaulvanDyk",
    instagram: "https://www.instagram.com/paulvandyk/",
    twitter: "https://x.com/paulvandyk",
    website: "https://www.paulvandyk.com/",
    bio: "Trance. Official paulvandyk.com — SC paulvandykofficial, YT @PaulvanDyk, IG @paulvandyk.",
  },
  {
    slug: "korolova",
    name: "Korolova",
    accent: "#f72585",
    soundcloud: "https://soundcloud.com/korolovadj",
    youtube: "https://www.youtube.com/@KOROLOVADJ",
    instagram: "https://www.instagram.com/korolova.dj/",
    website: "https://djmag.com/top100djs/2025/50/korolova",
    bio: "Melodic Techno. SC korolovadj, YT @KOROLOVADJ, IG @korolova.dj.",
  },
  {
    slug: "kolsch",
    name: "Kölsch",
    accent: "#ffd60a",
    soundcloud: "https://soundcloud.com/kolsch",
    youtube: "https://www.youtube.com/@KolschOfficial",
    instagram: "https://www.instagram.com/kolschofficial/",
    twitter: "https://x.com/kolschofficial",
    website: "https://www.kolschofficial.com/",
    bio: "Melodic Techno. Official kolschofficial.com — SC kolsch, YT @KolschOfficial, IG @kolschofficial.",
  },
  {
    slug: "miss-monique",
    name: "Miss Monique",
    accent: "#9b5de5",
    soundcloud: "https://soundcloud.com/alesia-arkusha",
    youtube: "https://www.youtube.com/@djmissmonique",
    instagram: "https://instagram.com/djmissmonique",
    twitter: "https://twitter.com/djmissmonique",
    website: "https://missmoniquemusic.com/",
    bio: "Melodic Techno. Official missmoniquemusic.com — SC alesia-arkusha, YT @djmissmonique, IG @djmissmonique.",
  },
  {
    slug: "ferry-corsten",
    name: "Ferry Corsten",
    accent: "#48cae4",
    soundcloud: "https://soundcloud.com/ferry-corsten",
    youtube: "https://www.youtube.com/@FerryCorsten",
    instagram: "https://www.instagram.com/ferrycorsten/",
    twitter: "https://x.com/ferrycorsten",
    website: "https://www.ferrycorsten.com/",
    bio: "Trance. Official ferrycorsten.com — SC ferry-corsten, YT @FerryCorsten, IG @ferrycorsten.",
  },
  {
    slug: "topic",
    name: "Topic",
    accent: "#fb8500",
    soundcloud: "https://soundcloud.com/topicmusic",
    youtube: "https://www.youtube.com/@topicmusictv",
    instagram: "https://www.instagram.com/topic/",
    website: "https://www.topic-music.com/",
    bio: "Dance. Official topic-music.com — SC topicmusic, YT @topicmusictv, IG @topic.",
  },
  {
    slug: "1788-l",
    name: "1788-L",
    accent: "#c1121f",
    soundcloud: null,
    youtube: "https://www.youtube.com/@1788L",
    instagram: "https://www.instagram.com/1788_l/",
    twitter: "https://x.com/l_1788",
    website: "https://1788-l.com",
    bio: "Riddim. United States. Official 1788-l.com — YT @1788L, IG @1788_l, X @l_1788. No official SoundCloud.",
  },
  {
    slug: "negitiv",
    name: "NEGITIV",
    accent: "#7b2cbf",
    soundcloud: "https://soundcloud.com/negitivofficial",
    youtube: "https://www.youtube.com/@negitivofficial",
    instagram: "https://www.instagram.com/negitiv/",
    website: "https://negitiv.com",
    bio: "Hard Techno. Cologne. Official negitiv.com — SC negitivofficial, YT @negitivofficial, IG @negitiv, booking BCB Family. 1001 sometimes credits Negativ.",
  },
  {
    slug: "mandy",
    name: "MANDY",
    accent: "#ff006e",
    soundcloud: null,
    youtube: "https://www.youtube.com/@mandyofficialbe",
    instagram: "https://www.instagram.com/mandyofficial_be/",
    twitter: "https://x.com/djmandyofficial",
    website: "https://www.youtube.com/@mandyofficialbe",
    bio: "Hard Dance / Hardstyle. Belgium. Official YT @mandyofficialbe — IG @mandyofficial_be, X @djmandyofficial. No official SoundCloud. Facebook on roster.",
  },
  {
    slug: "steve-angello",
    name: "Steve Angello",
    accent: "#e63946",
    soundcloud: "https://soundcloud.com/steveangello",
    youtube: "https://www.youtube.com/steveangello",
    instagram: "https://www.instagram.com/steveangello/",
    twitter: "https://x.com/SteveAngello",
    website: "https://www.steveangello.com/",
    bio: "Progressive House. Stockholm. Official steveangello.com — SC steveangello, YT /steveangello, IG @steveangello, X @SteveAngello. Facebook / TikTok / Spotify on roster.",
  },
];
