/**
 * Master roster of identified artists we want to deep-scan.
 * Single source of truth for YouTube / SoundCloud seeds + handle gaps.
 *
 * Curated entries live below; discovery can append graduates via
 * data/roster-graduates.json (see discovery/graduateRoster.ts).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { normalizeGenre, type CanonicalGenre } from "../genre";
import { slugify } from "./types";

export type HandleStatus = "ok" | "weak" | "missing" | "unverified";

export type ArtistRosterEntry = {
  name: string;
  genre: string;
  accent: string;
  homeCity?: string;
  youtube?: { handle: string; status: HandleStatus; note?: string };
  soundcloud?: {
    permalink: string;
    /** Optional — filled when known; adapters can resolve by permalink. */
    userId?: number;
    status: HandleStatus;
    note?: string;
  };
  website?: string;
  /** Other known social URLs (instagram, x, linktree) */
  socials?: string[];
  /** Deep-scan priority — higher artists get larger poll budgets */
  priority?: "high" | "normal";
};

function loadRosterGraduates(): ArtistRosterEntry[] {
  try {
    const path =
      process.env.ROSTER_GRADUATES_PATH ||
      join(
        /* turbopackIgnore: true */ process.cwd(),
        "data",
        "roster-graduates.json",
      );
    const parsed = JSON.parse(readFileSync(path, "utf8")) as {
      artists?: ArtistRosterEntry[];
    };
    return Array.isArray(parsed.artists) ? parsed.artists : [];
  } catch {
    return [];
  }
}

/**
 * Hand-curated seed artists. Prefer editing this list for known brand DJs.
 */
export const ARTIST_ROSTER_CURATED: ArtistRosterEntry[] = [
  // ---- High-signal tracklist / live publishers ----
  {
    name: "James Hype",
    genre: "Tech House",
    accent: "#ff3d6e",
    homeCity: "Liverpool, UK",
    youtube: { handle: "@JamesHype", status: "ok" },
    soundcloud: {
      permalink: "jameshypethedj",
      userId: 121047111,
      status: "ok",
      note: "canonical SC; jameshype is a weak/empty stub",
    },
    website: "https://www.jameshype.com",
    socials: [
      "https://www.youtube.com/channel/UCkAmFYllx331zGshdN4xPng",
      "https://www.youtube.com/watch?v=Ojw5OHHCk2I",
      "https://www.youtube.com/watch?v=rLTCLSsqrXY",
      "https://lnk.to/JH-TRIGGER",
      "https://soundcloud.com/jameshypethedj",
    ],
    priority: "high",
  },
  {
    name: "Tita Lau",
    genre: "Tech House",
    accent: "#ff8fab",
    youtube: { handle: "@TitaLau", status: "ok" },
    soundcloud: {
      permalink: "titalau",
      userId: 269011945,
      status: "weak",
      note: "0 tracks on SC profile",
    },
    priority: "high",
  },
  {
    name: "Chris Lake",
    genre: "Tech House",
    accent: "#3d8bfd",
    homeCity: "London, UK",
    youtube: { handle: "@ChrisLake", status: "ok" },
    soundcloud: { permalink: "chrislake", userId: 118319, status: "ok" },
    socials: ["https://instagram.com/chrislake", "https://twitter.com/chrislake"],
    priority: "high",
  },
  // ---- Beatportal House 2025 top-selling artists (chart QC) ----
  {
    name: "Luke Alessi",
    genre: "House",
    accent: "#ff8c42",
    homeCity: "Melbourne, AU",
    youtube: { handle: "@luke.alessi", status: "ok" },
    soundcloud: { permalink: "lukealessiofficial", status: "ok" },
    socials: ["https://soundcloud.com/lukealessiofficial"],
    priority: "high",
  },
  {
    name: "Chloé Caillet",
    genre: "House",
    accent: "#ff6fb0",
    homeCity: "London, UK",
    soundcloud: { permalink: "chloecaillet", status: "ok" },
    socials: [
      "https://soundcloud.com/chloecaillet",
      "https://www.instagram.com/chloecaillet/",
      "https://chloecaillet.bandcamp.com/",
    ],
    priority: "high",
  },
  {
    name: "Jocelyn Brown",
    genre: "House",
    accent: "#f4c560",
    // Vocalist — no deep-scan handles; kept for chart / track credit QC.
    priority: "normal",
  },
  {
    name: "Malive",
    genre: "House",
    accent: "#2bd67b",
    youtube: { handle: "@malive", status: "ok" },
    soundcloud: { permalink: "maliveofficial", status: "ok" },
    priority: "high",
  },
  {
    name: "Jonas Blue",
    genre: "House",
    accent: "#3aa0e0",
    soundcloud: { permalink: "jonasblue", status: "ok" },
    socials: ["https://soundcloud.com/jonasblue"],
    priority: "high",
  },
  {
    name: "Kolter",
    genre: "House",
    accent: "#8a7cff",
    youtube: { handle: "@koltermusic", status: "ok" },
    soundcloud: { permalink: "kolter", status: "ok" },
    priority: "high",
  },
  {
    name: "Crusy",
    genre: "House",
    accent: "#ff4d6d",
    youtube: { handle: "@Crusy", status: "ok" },
    soundcloud: { permalink: "crusyofficial", status: "ok" },
    priority: "high",
  },
  {
    name: "David Penn",
    genre: "House",
    accent: "#45c7e0",
    youtube: { handle: "@davidpenn", status: "ok" },
    priority: "normal",
  },
  {
    name: "Luke Dean",
    genre: "House",
    accent: "#f5a623",
    youtube: { handle: "@LukeDean", status: "ok" },
    soundcloud: { permalink: "lukedean", status: "ok" },
    priority: "normal",
  },
  {
    name: "The Shapeshifters",
    genre: "House",
    accent: "#7c5cff",
    youtube: { handle: "@TheShapeshifters", status: "ok" },
    soundcloud: { permalink: "theshapeshifters", status: "ok" },
    priority: "normal",
  },
  {
    name: "Tripolism",
    genre: "House",
    accent: "#00e5ff",
    youtube: { handle: "@tripolism", status: "ok" },
    soundcloud: { permalink: "tripolism", status: "ok" },
    priority: "normal",
  },
  {
    name: "Vinter",
    genre: "House",
    accent: "#b48cff",
    youtube: { handle: "@vinter", status: "ok" },
    priority: "normal",
  },
  {
    name: "Samm",
    genre: "House",
    accent: "#2a9d8f",
    soundcloud: { permalink: "sammbe", status: "ok" },
    priority: "normal",
  },
  {
    name: "FISHER",
    genre: "Tech House",
    accent: "#00c2ff",
    youtube: { handle: "@fisher", status: "ok" },
    soundcloud: {
      permalink: "fish-tales",
      userId: 289944,
      status: "ok",
      note: "official SC (followthefishtv.com in bio)",
    },
    website: "https://followthefishtv.com",
    socials: [
      "https://www.instagram.com/followthefishtv/",
      "https://tiktok.com/@FISHER",
      "https://facebook.com/followthefishtv.tv",
      "https://soundcloud.com/fish-tales",
      "https://www.youtube.com/@fisher",
      "https://open.spotify.com/artist/1VJ0briNOlXRtJUAzoUJdt",
    ],
    priority: "high",
  },
  {
    name: "Oliver Heldens",
    genre: "Future House",
    accent: "#7c5cff",
    homeCity: "Netherlands",
    youtube: { handle: "@OliverHeldens", status: "ok" },
    soundcloud: { permalink: "oliverheldens", userId: 2279060, status: "ok" },
    socials: [
      "http://instagram.com/heldeeprecords/",
      "http://soundcloud.com/HeldeepRecords/",
    ],
    priority: "high",
  },
  {
    name: "Vintage Culture",
    genre: "Tech House",
    accent: "#e85d04",
    homeCity: "Brazil",
    youtube: { handle: "@VintageCulture", status: "ok" },
    soundcloud: {
      permalink: "vintageculturemusic",
      userId: 15708649,
      status: "ok",
    },
    website: "https://vintageculture.com",
    socials: [
      "https://www.instagram.com/vintageculture/",
      "https://www.facebook.com/vintageculturemusic/",
      "https://x.com/VintageCulture",
      "https://www.tiktok.com/@vintageculture",
      "https://open.spotify.com/artist/28uJnu5EsrGml2tBd7y8ts",
      "https://soundcloud.com/vintageculturemusic",
      "https://www.youtube.com/@VintageCulture",
      "https://vintageculture.com",
    ],
    priority: "high",
  },
  {
    name: "MEDUZA",
    genre: "House",
    accent: "#5cc7e8",
    homeCity: "Italy",
    youtube: { handle: "@meduzamusic", status: "ok" },
    soundcloud: { permalink: "meduzamusic", userId: 572691174, status: "ok" },
    priority: "normal",
  },
  {
    name: "Wax Motif",
    genre: "G-House",
    accent: "#c56cff",
    youtube: { handle: "@WaxMotif", status: "ok" },
    soundcloud: { permalink: "waxmotif", userId: 11978, status: "ok" },
    priority: "high",
  },
  {
    name: "John Summit",
    genre: "Tech House",
    accent: "#7cffb2",
    homeCity: "Chicago, US",
    youtube: { handle: "@johnsummit", status: "ok" },
    soundcloud: { permalink: "johnsummit", userId: 173854108, status: "ok" },
    priority: "high",
  },
  {
    name: "Cloonee",
    genre: "Tech House",
    accent: "#f08a3d",
    youtube: { handle: "@cloonee", status: "ok" },
    soundcloud: { permalink: "cloonee", userId: 78975954, status: "ok" },
    priority: "high",
  },
  {
    name: "Gorgon City",
    genre: "House",
    accent: "#f15bb5",
    youtube: { handle: "@GorgonCity", status: "ok" },
    soundcloud: { permalink: "gorgon-city", userId: 12172879, status: "ok" },
    priority: "normal",
  },
  {
    name: "Walker & Royce",
    genre: "Tech House",
    accent: "#9ef01a",
    homeCity: "New York, US",
    youtube: { handle: "@WalkerAndRoyce", status: "ok" },
    soundcloud: {
      permalink: "walker-and-royce",
      userId: 7055425,
      status: "ok",
    },
    website: "https://www.walkerandroyce.com/",
    socials: [
      "https://www.walkerandroyce.com/",
      "https://www.instagram.com/walkerandroyce/",
      "https://www.facebook.com/walkerroyce/",
      "https://x.com/WalkerAndRoyce",
      "https://www.tiktok.com/@walkerandroyce",
      "https://open.spotify.com/artist/1lAwVq9MxNJkB0dEY6xNoV",
      "https://soundcloud.com/walker-and-royce",
      "https://www.youtube.com/@WalkerAndRoyce",
    ],
    priority: "high",
  },
  {
    name: "Hot Since 82",
    genre: "Tech House",
    accent: "#e9c46a",
    homeCity: "Leeds, UK",
    youtube: { handle: "@HotSince82", status: "ok" },
    soundcloud: { permalink: "hotsince-82", userId: 5646032, status: "ok" },
    website: "https://hotsince82.com",
    socials: [
      "https://hotsince82.com",
      "https://www.facebook.com/hotsince82",
      "https://x.com/hotsince82",
      "https://soundcloud.com/hotsince-82",
      "https://www.beatport.com/artist/hot-since-82/212422",
      "https://www.youtube.com/@HotSince82",
    ],
    priority: "high",
  },
  {
    name: "Adam Beyer",
    genre: "Techno",
    accent: "#111111",
    youtube: { handle: "@adambeyer", status: "ok" },
    socials: [
      "https://www.instagram.com/realadambeyer/",
      "https://www.tiktok.com/@adamdrumcodebeyer",
      "https://open.spotify.com/artist/1btv9qmIpbp7q1ixCYNdHu",
      "https://www.youtube.com/@adambeyer",
    ],
    priority: "high",
  },
  {
    name: "DIJON",
    genre: "House",
    accent: "#f4a261",
    youtube: { handle: "@dijon", status: "ok" },
    website: "https://dijondijon.com",
    socials: [
      "https://dijondijon.com",
      "https://www.instagram.com/dijondijon_/",
      "https://x.com/dijondijon_",
      "https://www.youtube.com/@dijon",
      "https://www.youtube.com/c/DIJONDIJON",
    ],
    priority: "normal",
  },
  {
    name: "Max Styler",
    genre: "Tech House",
    accent: "#ff9f1c",
    youtube: { handle: "@MaxStyler", status: "ok" },
    soundcloud: { permalink: "maxstyler", userId: 8834846, status: "ok" },
    // Homepage-visible SC lives with sparse ID comments — raise enrich demand.
    priority: "high",
  },
  {
    name: "Hannah Laing",
    genre: "Techno",
    accent: "#ff006e",
    youtube: { handle: "@HannahLaingDJ", status: "ok" },
    soundcloud: {
      permalink: "hannahlaingdj",
      userId: 5008420,
      status: "ok",
    },
    priority: "high",
  },
  {
    name: "PAWSA",
    genre: "Tech House",
    accent: "#adb5bd",
    youtube: { handle: "@PAWSA", status: "ok" },
    soundcloud: { permalink: "pawsa", userId: 2265457, status: "ok" },
    priority: "high",
  },
  {
    name: "Bleu Clair",
    genre: "Tech House",
    accent: "#4cc9f0",
    homeCity: "Indonesia",
    youtube: { handle: "@bleuclairmusic", status: "ok" },
    soundcloud: { permalink: "bleuclair", userId: 20599284, status: "ok" },
    socials: [
      "https://www.instagram.com/bleuclairmusic/",
      "https://www.facebook.com/bleuclairmusic/",
      "https://x.com/bleuclair",
      "https://www.tiktok.com/@bleuclairmusic",
      "https://open.spotify.com/artist/7kA4sEagpoNK91I7wr9tYr",
      "https://soundcloud.com/bleuclair",
      "https://www.youtube.com/@bleuclairmusic",
    ],
    priority: "high",
  },
  {
    name: "BIJOU",
    genre: "G-House",
    accent: "#ff5c8a",
    homeCity: "Los Angeles, US",
    youtube: { handle: "@BIJOU", status: "ok" },
    soundcloud: { permalink: "bijou", userId: 2080568, status: "ok" },
    priority: "normal",
  },
  {
    name: "Prospa",
    genre: "House",
    accent: "#ffd166",
    youtube: { handle: "@ProspaUK", status: "ok" },
    soundcloud: { permalink: "prospauk", userId: 69483974, status: "ok" },
    socials: ["https://www.youtube.com/channel/UCMasYklV4R1r6q3-YeBSnwQ"],
    priority: "normal",
  },
  {
    name: "SIDEPIECE",
    genre: "Tech House",
    accent: "#fee440",
    youtube: { handle: "@youasidepiece", status: "ok" },
    soundcloud: { permalink: "sidepiece", userId: 647038533, status: "ok" },
    website: "https://hoo.be/youasidepiece",
    socials: [
      "https://www.youtube.com/@youasidepiece",
      "https://www.youtube.com/channel/UC4CFtujFMNGXRixR5tCPKdQ",
      "https://instagram.com/sidepiece",
      "https://twitter.com/youasidepiece",
      "https://open.spotify.com/artist/5czbzNZZfWpyFgZyfT3Mkk",
      "https://lnk.to/CLR019",
    ],
    priority: "high",
  },
  {
    name: "Sammy Virji",
    genre: "UK Garage",
    accent: "#00f5d4",
    youtube: { handle: "@SammyVirji", status: "ok" },
    soundcloud: { permalink: "sammyvirji", userId: 33443491, status: "ok" },
    priority: "normal",
  },
  {
    name: "BISCITS",
    genre: "Tech House",
    accent: "#ef476f",
    youtube: { handle: "@Biscits", status: "ok" },
    soundcloud: { permalink: "biscits", userId: 275644376, status: "ok" },
    // Canonical About links (IG handle is itsbiscits — not @biscits).
    socials: [
      "https://www.instagram.com/itsbiscits/",
      "https://www.facebook.com/biscits/",
      "https://soundcloud.com/biscits",
      "https://open.spotify.com/artist/052B9SONfhoScw7dgYWw5o",
      "https://www.beatport.com/artist/biscits/591990",
      "https://www.youtube.com/@Biscits",
    ],
    priority: "high",
  },
  {
    name: "Mau P",
    genre: "Tech House",
    accent: "#118ab2",
    youtube: { handle: "@maupmusic", status: "ok" },
    soundcloud: { permalink: "realmaup", userId: 1154700529, status: "ok" },
    socials: [
      "https://www.youtube.com/@maupmusic",
      "https://soundcloud.com/realmaup",
      "https://instagram.com/maupmusic",
      "https://twitter.com/realmaup",
    ],
    priority: "high",
  },
  {
    name: "CID",
    genre: "Tech House",
    accent: "#45c7e0",
    homeCity: "United States",
    youtube: { handle: "@CIDmusic", status: "ok" },
    soundcloud: { permalink: "cidmusic", userId: 381684, status: "ok" },
    website: "https://www.cidmusic.com/",
    socials: [
      "https://www.youtube.com/@CIDmusic",
      "https://soundcloud.com/cidmusic",
      "https://cid.komi.io/",
      "https://instagram.com/cidmusic",
      "https://twitter.com/cidmusic",
      "https://fb.com/CIDofficial",
    ],
    priority: "high",
  },
  {
    name: "BRANDON",
    genre: "Tech House",
    accent: "#ff5e5e",
    homeCity: "Germany",
    youtube: { handle: "@BRANDONSOUNDS", status: "ok" },
    soundcloud: { permalink: "brandonsounds", userId: 426298821, status: "ok" },
    website: "https://brandon-sounds.com/",
    socials: [
      "https://www.youtube.com/@BRANDONSOUNDS",
      "https://soundcloud.com/brandonsounds",
      "https://instagram.com/brandonsounds",
      "https://tiktok.com/@brandonsounds",
      "https://facebook.com/allaboutbrandon",
      "https://open.spotify.com/artist/7HHxWuXHsKdcTbWDqqYbsY",
      "https://music.apple.com/de/artist/brandon/1493109644",
      "https://www.beatport.com/artist/brandon/274157",
    ],
    priority: "high",
  },
  {
    name: "Black Coffee",
    genre: "Afro House",
    accent: "#222222",
    homeCity: "South Africa",
    youtube: { handle: "@realblackcoffee", status: "ok" },
    soundcloud: {
      permalink: "realblackcoffee",
      userId: 4941960,
      status: "ok",
    },
    socials: [
      "https://www.instagram.com/realblackcoffee/",
      "https://www.facebook.com/realblackcoffee/",
      "https://x.com/RealBlackCoffee",
      "https://music.apple.com/za/artist/black-coffee/306140760",
      "https://open.spotify.com/artist/6wMr4zKPrrR0UVz08WtUWc",
      "https://soundcloud.com/realblackcoffee",
      "https://www.youtube.com/@realblackcoffee",
    ],
    priority: "high",
  },
  {
    name: "Chapter & Verse",
    genre: "Tech House",
    accent: "#f77f00",
    homeCity: "UK",
    youtube: {
      handle: "@chapterandversemusic",
      status: "weak",
      note: "releases / interview on YT; sets via curated SC guestmix seeds",
    },
    soundcloud: {
      permalink: "chapterandverseofficial",
      userId: 701819711,
      status: "weak",
      note: "profile is singles-only; sets via SOUNDCLOUD_TRACK_SEEDS",
    },
    socials: [
      "https://soundcloud.com/chapterandverseofficial",
      "https://www.youtube.com/@chapterandversemusic",
    ],
    priority: "high",
  },
  {
    name: "AC Slater",
    genre: "Bass House",
    accent: "#f2b33d",
    homeCity: "Los Angeles, US",
    // Canonical YT is user/djacslater → @djacslater (@ACSlater is unrelated).
    youtube: { handle: "@djacslater", status: "ok" },
    soundcloud: { permalink: "acslater", userId: 1423532, status: "ok" },
    website: "https://www.djacslater.com/",
    socials: [
      "https://www.instagram.com/djacslater/",
      "https://www.youtube.com/user/djacslater",
      "https://www.youtube.com/@djacslater",
      "https://open.spotify.com/artist/6EqFMCnVGBRNmwPlk2f3Uc",
      "https://www.beatport.com/artist/ac-slater/52351",
      "https://www.insomniac.com/music/artists/ac-slater/",
    ],
    // Similar Bass House cluster with Marten Horger / bradeazy.
    priority: "high",
  },
  {
    name: "Marten Horger",
    genre: "Bass House",
    accent: "#ff7a45",
    homeCity: "Berlin, DE",
    youtube: { handle: "@MARTENHORGER", status: "ok" },
    soundcloud: { permalink: "marten-horger", userId: 242146, status: "ok" },
    website: "https://www.martenhorger.com/",
    socials: [
      "https://www.martenhorger.com/",
      "https://facebook.com/marten.horger",
      "https://instagram.com/marten_horger",
      "https://www.tiktok.com/@MARTENHORGER",
      "https://www.youtube.com/@MARTENHORGER",
      "https://soundcloud.com/marten-horger",
      "https://open.spotify.com/artist/0EdUwJSqkMmsH6Agg3G8Ls",
    ],
    priority: "high",
  },
  {
    // Anchor favorite (aka "breazly").
    name: "bradeazy",
    genre: "Bass House",
    accent: "#3aa0e0",
    homeCity: "Miami, US",
    youtube: { handle: "@bradeazy", status: "ok" },
    soundcloud: { permalink: "bradeazy", userId: 1125867328, status: "ok" },
    website: "https://hoo.be/bradeazy",
    socials: [
      "https://www.youtube.com/@bradeazy",
      "https://soundcloud.com/bradeazy",
      "https://instagram.com/bradeazy",
      "https://tiktok.com/@bradeazy",
      "https://open.spotify.com/artist/1dESZUZevzhd5dzq9ZsMLI",
      "https://www.beatport.com/artist/bradeazy/1251128",
    ],
    priority: "high",
  },
  {
    name: "David Guetta",
    genre: "House",
    accent: "#1e90ff",
    homeCity: "Paris, FR",
    youtube: { handle: "@davidguetta", status: "ok" },
    soundcloud: {
      permalink: "davidguetta",
      userId: 4904351,
      status: "ok",
      note: "live SC userId (was stale 201859)",
    },
    website: "https://davidguetta.com",
    socials: [
      "https://www.instagram.com/davidguetta/",
      "https://x.com/davidguetta",
      "https://soundcloud.com/davidguetta",
      "https://www.youtube.com/@davidguetta",
      "https://open.spotify.com/artist/1Cs0zKBU1kc0i8ypK3B9ai",
    ],
    priority: "high",
  },
  {
    name: "Armin van Buuren",
    genre: "Trance",
    accent: "#00a3e0",
    homeCity: "Netherlands",
    youtube: { handle: "@arminvanbuuren", status: "ok" },
    soundcloud: { permalink: "arminvanbuuren", status: "ok" },
    website: "https://www.arminvanbuuren.com/",
    socials: [
      "https://www.arminvanbuuren.com/",
      "https://www.youtube.com/@arminvanbuuren",
      "https://www.instagram.com/arminvanbuuren",
      "https://twitter.com/arminvanbuuren",
      "https://www.tiktok.com/@arminvanbuuren",
      "https://www.facebook.com/arminvanbuuren",
      "https://open.spotify.com/artist/0SfsnGyD8FplN4U4WCkBZ5",
      "https://soundcloud.com/arminvanbuuren",
      "https://discord.gg/arminvanbuuren",
    ],
    priority: "high",
  },
  {
    name: "ARTBAT",
    genre: "Melodic Techno",
    accent: "#6c63ff",
    homeCity: "Kyiv, UA",
    youtube: { handle: "@ARTBAT", status: "ok" },
    soundcloud: {
      permalink: "artbatmusic",
      userId: 14008227,
      status: "ok",
    },
    website: "https://www.beatport.com/artist/artbat/499932",
    socials: [
      "https://www.instagram.com/artbatmusic/",
      "https://soundcloud.com/artbatmusic",
      "https://www.youtube.com/@ARTBAT",
      "https://open.spotify.com/artist/3BkRu2TGd2I1uBxZKddfg1",
      "https://www.beatport.com/artist/artbat/499932",
      "https://ra.co/dj/Artbat/tour-dates",
    ],
    priority: "high",
  },
  {
    name: "Bizarrap",
    genre: "House",
    accent: "#f4a261",
    homeCity: "Ramos Mejía, AR",
    youtube: { handle: "@Bizarrap", status: "ok" },
    soundcloud: {
      permalink: "bizarrap",
      userId: 302974540,
      status: "ok",
    },
    socials: [
      "https://www.instagram.com/bizarrap/",
      "https://soundcloud.com/bizarrap",
      "https://www.youtube.com/@Bizarrap",
      "https://open.spotify.com/artist/716NhGYqD1jl2wI1Qkgq36",
    ],
    priority: "high",
  },
  {
    name: "Men Machine",
    genre: "Bass House",
    accent: "#ff4d6d",
    homeCity: "Paris / Berlin",
    // Project alias for Guetta × Horger — poll when handles resolve.
    youtube: { handle: "@davidguetta", status: "weak", note: "project under Guetta channel for now" },
    soundcloud: {
      permalink: "davidguetta",
      userId: 4904351,
      status: "weak",
      note: "project releases often land on Guetta SC",
    },
    priority: "normal",
  },
  {
    name: "Dom Dolla",
    genre: "Tech House",
    accent: "#ff4d6d",
    homeCity: "Melbourne, AU",
    youtube: { handle: "@DomDolla", status: "ok" },
    soundcloud: { permalink: "domdolla", userId: 627109, status: "ok" },
    website: "https://domdolla.com.au",
    socials: [
      "https://domdolla.com.au",
      "https://www.instagram.com/domdolla/",
      "https://x.com/domdolla",
      "https://www.facebook.com/domdollamusic",
      "https://www.tiktok.com/@domdolla",
      "https://open.spotify.com/artist/205i7E8fNVfojowcQSfK9m",
      "https://soundcloud.com/domdolla",
      "https://www.youtube.com/@DomDolla",
    ],
    priority: "high",
  },
  {
    name: "Chris Lorenzo",
    // Songstats tags: Tech House (+ House / Electronic / EDM / Club)
    genre: "Tech House",
    accent: "#ff6b35",
    homeCity: "UK",
    youtube: { handle: "@ChrisLorenzo", status: "ok" },
    soundcloud: {
      permalink: "chris-lorenzo-1",
      userId: 828225,
      status: "ok",
    },
    website: "https://chrislorenzo.komi.io",
    socials: [
      "https://chrislorenzo.komi.io",
      "https://www.instagram.com/chrislorenzo66/",
      "https://x.com/Lorenzosbeats",
      "https://www.facebook.com/chrislorenzo88",
      "https://open.spotify.com/artist/7tm9Tuc70geXOOyKhtZHIj",
      "https://soundcloud.com/chris-lorenzo-1",
      "https://www.youtube.com/@ChrisLorenzo",
    ],
    priority: "high",
  },
  {
    // Chris Lake + Chris Lorenzo project — anchor favorite.
    // Official SC/YT are release clips only (no crawlable full sets yet).
    // Coachella 2024 was livestream-only; no official archive on SC/YT.
    name: "Anti Up",
    genre: "Tech House",
    accent: "#ff006e",
    youtube: {
      handle: "@antiup",
      status: "weak",
      note: "shorts/clips only; full sets not on official channel",
    },
    soundcloud: {
      permalink: "antiupmusic",
      userId: 399166893,
      status: "weak",
      note: "singles/extended mixes only; no official long-form sets",
    },
    socials: [
      "https://www.youtube.com/@antiup",
      "https://soundcloud.com/antiupmusic",
      "https://www.instagram.com/antiupmusic/",
      "https://www.facebook.com/antiupmusic/",
      "https://twitter.com/antiupmusic",
      "https://open.spotify.com/artist/4UwR1ir6PovnQiwX5jRPvF",
    ],
    priority: "high",
  },
  {
    name: "Hannah Wants",
    genre: "Tech House",
    accent: "#ff4d8d",
    homeCity: "UK",
    youtube: { handle: "@HannahWantsDJ", status: "ok" },
    soundcloud: {
      permalink: "hannah_wants",
      userId: 72049,
      status: "ok",
    },
    socials: [
      "https://www.instagram.com/hannah_wants/",
      "https://x.com/hannah_wants",
      "https://www.facebook.com/hannahwantsdj",
      "https://soundcloud.com/hannah_wants",
      "https://www.youtube.com/@HannahWantsDJ",
      "https://open.spotify.com/artist/7sK4hnuUOXw6VStDw0q8NI",
      "https://www.beatport.com/artist/hannah-wants/194849",
    ],
    priority: "high",
  },
  {
    name: "Dimitri Vegas & Like Mike",
    genre: "Big Room",
    accent: "#f7b801",
    homeCity: "Belgium",
    youtube: { handle: "@dimitrivegasandlikemike", status: "ok" },
    soundcloud: {
      permalink: "dimitrivegasandlikemike",
      userId: 274197,
      status: "ok",
    },
    socials: [
      "https://www.instagram.com/dimitrivegasandlikemike/",
      "https://www.facebook.com/dimitrivegasandlikemike",
      "https://www.tiktok.com/@dimitrivegasandlikemike",
      "https://soundcloud.com/dimitrivegasandlikemike",
      "https://www.youtube.com/@dimitrivegasandlikemike",
    ],
    priority: "high",
  },
  {
    name: "Msendy",
    genre: "Deep House",
    accent: "#2a9d8f",
    soundcloud: { permalink: "msandi", userId: 1485141, status: "ok" },
    website: "https://www.mixcloud.com/Msendy/",
    socials: [
      "https://www.mixcloud.com/Msendy/",
      "https://soundcloud.com/msandi",
      "https://hearthis.at/tjzqnmf7",
    ],
    priority: "normal",
  },
  {
    name: "Odd Mob",
    genre: "Tech House",
    accent: "#b8f200",
    homeCity: "Brisbane, AU",
    youtube: { handle: "@oddmob", status: "ok" },
    soundcloud: { permalink: "oddmob", userId: 34486918, status: "ok" },
    socials: [
      "https://soundcloud.com/oddmob",
      "https://www.instagram.com/odd_mob/",
      "https://www.youtube.com/@oddmob",
      "https://open.spotify.com/artist/4qLwtWhlhyAoQ4S9mSrDW9",
      "https://www.youtube.com/watch?v=ObiAocVMTyo",
    ],
    // Similar to CID / Chris Lorenzo / SIDEPIECE tech-house cluster.
    priority: "high",
  },
  {
    name: "Westend",
    genre: "Tech House",
    accent: "#f72585",
    homeCity: "New York, US",
    youtube: { handle: "@itsthewestend", status: "ok" },
    soundcloud: {
      permalink: "itsthewestend",
      userId: 29027639,
      status: "ok",
      note: "canonical SC; westend is a different/empty account",
    },
    socials: [
      "https://soundcloud.com/itsthewestend",
      "https://www.youtube.com/@itsthewestend",
      "https://www.beatport.com/artist/westend/576028",
    ],
    // Similar to Dom Dolla / Mau P / Chris Lake festival tech house.
    priority: "high",
  },
  {
    name: "Sara Landry",
    genre: "Techno",
    accent: "#9b5de5",
    youtube: { handle: "@saralandry922", status: "ok" },
    soundcloud: {
      permalink: "sara-landry-dj",
      userId: 93585668,
      status: "ok",
    },
    website: "https://www.saralandry.com",
    socials: [
      "https://soundcloud.com/sara-landry-dj",
      "https://www.youtube.com/@saralandry922",
      "https://www.instagram.com/saralandrydj/",
      "https://www.beatport.com/artist/sara-landry/663399",
      "https://www.saralandry.com",
    ],
    priority: "normal",
  },
  {
    name: "Lilly Palmer",
    genre: "Techno",
    accent: "#ff006e",
    youtube: { handle: "@lillypalmer_dj", status: "ok" },
    soundcloud: {
      permalink: "lilly_palmer",
      userId: 193213281,
      status: "ok",
    },
    socials: [
      "https://soundcloud.com/lilly_palmer",
      "https://www.instagram.com/lilly_palmerdj/",
      "https://www.facebook.com/lillypalmer.dj",
      "https://www.tiktok.com/@lillypalmerdj",
      "https://www.youtube.com/@lillypalmer_dj",
      "https://www.beatport.com/artist/lilly-palmer/597345",
    ],
    priority: "normal",
  },
  {
    name: "Tape B",
    genre: "Bass House",
    accent: "#ffbe0b",
    youtube: { handle: "@tapebbeats", status: "ok" },
    soundcloud: {
      permalink: "tape-b-official",
      userId: 38123548,
      status: "ok",
    },
    website: "https://linktr.ee/tapebbeats",
    socials: [
      "https://soundcloud.com/tape-b-official",
      "https://www.youtube.com/@tapebbeats",
      "https://linktr.ee/tapebbeats",
    ],
    priority: "normal",
  },
  {
    name: "HNTR",
    genre: "Techno",
    accent: "#00f5d4",
    homeCity: "Toronto, CA",
    youtube: { handle: "@hntrnet", status: "ok" },
    soundcloud: {
      permalink: "hntrnet",
      userId: 41184115,
      status: "ok",
      note: "canonical SC hntrnet — soundcloud.com/hntr is a different user",
    },
    website: "https://www.hntr.net",
    socials: [
      "https://www.hntr.net",
      "https://soundcloud.com/hntrnet",
      "https://www.instagram.com/hntrnet/",
      "https://www.facebook.com/hntrnet",
      "https://twitter.com/hntrnet",
      "https://www.youtube.com/@hntrnet",
      "https://noneon.com",
    ],
    priority: "normal",
  },
  {
    name: "Layton Giordani",
    genre: "Techno",
    accent: "#4cc9f0",
    youtube: { handle: "@LaytonGiordani", status: "unverified" },
    soundcloud: {
      permalink: "laytongiordani",
      userId: 66586175,
      status: "ok",
    },
    priority: "normal",
  },
  {
    name: "Charlotte de Witte",
    genre: "Techno",
    accent: "#e0e0e0",
    homeCity: "Belgium",
    youtube: { handle: "@charlottedewittemusic", status: "ok" },
    soundcloud: {
      permalink: "charlottedewittemusic",
      userId: 200516,
      status: "ok",
    },
    website: "https://charlottedewittemusic.com",
    socials: [
      "https://charlottedewittemusic.com",
      "https://www.instagram.com/charlottedewittemusic",
      "https://www.tiktok.com/@charlottedewittemusic",
      "https://soundcloud.com/charlottedewittemusic",
      "https://www.facebook.com/charlottedewittemusic",
      "https://twitter.com/charlottedwitte",
      "https://www.youtube.com/@charlottedewittemusic",
    ],
    priority: "high",
  },
  {
    name: "Solomun",
    genre: "Melodic House",
    accent: "#f0e6d8",
    homeCity: "Hamburg, DE",
    youtube: { handle: "@SolomunOfficial", status: "ok" },
    soundcloud: { permalink: "solomun", userId: 4545, status: "ok" },
    website: "https://solomun.org/",
    socials: [
      "https://solomun.org/",
      "https://www.instagram.com/solomun/",
      "https://www.facebook.com/SolomunMusic",
      "https://www.youtube.com/@SolomunOfficial",
      "https://www.tiktok.com/@solomun",
      "https://open.spotify.com/artist/5wJK4kQAkVGjqM9x46KQOC",
      "https://www.beatport.com/artist/solomun/25648",
      "https://music.apple.com/artist/solomun/200779145",
      "https://www.youtube.com/watch?v=g1vH9C_o-vo",
    ],
    priority: "normal",
  },
  {
    name: "Robin Schulz",
    genre: "House",
    accent: "#5aa9e6",
    homeCity: "Germany",
    youtube: { handle: "@robinschulz", status: "ok" },
    soundcloud: { permalink: "robin-schulz", userId: 7293319, status: "ok" },
    website: "https://robin-schulz.com",
    socials: [
      "https://facebook.com/robin.schulz.official",
      "https://instagram.com/robin__schulz",
      "https://tiktok.com/@robinschulzofficial",
      "https://twitter.com/robin_schulz",
      "https://open.spotify.com/artist/3t5xRXzsuZmMDkQzgOX35S",
      "https://music.apple.com/de/artist/robin-schulz/347433400",
      "https://www.youtube.com/@robinschulz",
      "https://soundcloud.com/robin-schulz",
    ],
    priority: "high",
  },
  {
    name: "Keinemusik",
    genre: "Afro House",
    accent: "#e8c547",
    homeCity: "Berlin, DE",
    youtube: { handle: "@keinemusik", status: "ok" },
    soundcloud: { permalink: "keinemusik", userId: 42109, status: "ok" },
    socials: ["https://ffm.to/km074"],
    priority: "normal",
  },
  {
    name: "Gentlemen's Groove",
    genre: "Deep House",
    accent: "#00e5ff",
    homeCity: "South Africa",
    // Long mixes live on hearthis; SC is the label singles account.
    soundcloud: {
      permalink: "gentlemens-groove-records",
      userId: 13671588,
      status: "ok",
    },
    website: "https://www.facebook.com/Gentlemensgroove",
    socials: [
      "https://hearthis.at/gentlemensgroove-oz/",
      "https://www.facebook.com/Gentlemensgroove",
    ],
    priority: "normal",
  },
  // ---- DJ Mag Top 100 coverage (missing sets / handle gaps) ----
  {
    // Verified 2026-07-31 from YT About link block.
    name: "Fred again...",
    genre: "House",
    accent: "#adb5bd",
    homeCity: "United Kingdom",
    youtube: { handle: "@Fredagainagain", status: "ok" },
    soundcloud: {
      permalink: "fredagain",
      userId: 637643742,
      status: "ok",
    },
    socials: [
      "https://www.youtube.com/@Fredagainagain",
      "https://soundcloud.com/fredagain",
      "https://instagram.com/fredagainagainagainagainagain",
      "https://tiktok.com/@fredagainagain",
      "https://fredagain.lnk.to/community",
    ],
    priority: "high",
  },
  {
    // Verified 2026-07-31 from YT About — SC lo-freq-1 (not empty lostfrequencies).
    name: "Lost Frequencies",
    genre: "Melodic House",
    accent: "#4cc9f0",
    homeCity: "Belgium",
    youtube: { handle: "@LostFrequencies", status: "ok" },
    soundcloud: {
      permalink: "lo-freq-1",
      userId: 29986752,
      status: "ok",
    },
    website: "https://lostfrequencies.com/",
    socials: [
      "https://www.youtube.com/@LostFrequencies",
      "https://soundcloud.com/lo-freq-1",
      "https://instagram.com/lostfrequencies",
      "https://tiktok.com/@lostfrequencies",
      "https://facebook.com/LostFrequenciesMusic",
      "https://x.com/lfrequencies",
    ],
    priority: "high",
  },
  {
    // Verified 2026-07-31 from YT About — artist SC maddixmusic (not Extatic label).
    name: "Maddix",
    genre: "Techno",
    accent: "#7b2cbf",
    homeCity: "Utrecht, Netherlands",
    youtube: { handle: "@maddixmusic", status: "ok" },
    soundcloud: {
      permalink: "maddixmusic",
      userId: 119258,
      status: "ok",
      note: "not extaticrecords (label account)",
    },
    website: "https://maddixmusic.com",
    socials: [
      "https://www.youtube.com/@maddixmusic",
      "https://soundcloud.com/maddixmusic",
      "https://instagram.com/maddixmusic",
      "https://tiktok.com/@maddixmusic",
      "https://twitter.com/MaddixMusic",
      "https://facebook.com/maddixmusic",
    ],
    priority: "high",
  },
  // Remaining Top 100 off deep-scan roster (handles verified 2026-07-31).
  {
    name: "Martin Garrix",
    genre: "Big Room",
    accent: "#ff9f1c",
    homeCity: "The Netherlands",
    youtube: { handle: "@MartinGarrix", status: "ok" },
    soundcloud: {
      permalink: "martingarrix",
      userId: 2068138,
      status: "ok",
    },
    website: "https://martingarrix.com/",
    socials: [
      "https://www.youtube.com/@MartinGarrix",
      "https://soundcloud.com/martingarrix",
    ],
    priority: "high",
  },
  {
    name: "Don Diablo",
    genre: "Future House",
    accent: "#ff006e",
    homeCity: "The Netherlands",
    youtube: { handle: "@DonDiablo", status: "ok" },
    soundcloud: {
      permalink: "dondiablo",
      userId: 31037,
      status: "ok",
    },
    website: "https://www.dondiablo.com/",
    socials: [
      "https://www.youtube.com/@DonDiablo",
      "https://soundcloud.com/dondiablo",
    ],
    priority: "high",
  },
  {
    name: "Steve Aoki",
    genre: "Electro House",
    accent: "#3a86ff",
    homeCity: "California",
    youtube: { handle: "@SteveAoki", status: "ok" },
    soundcloud: {
      permalink: "steveaoki",
      userId: 199197,
      status: "ok",
    },
    website: "https://www.steveaoki.com/",
    socials: [
      "https://www.youtube.com/@SteveAoki",
      "https://soundcloud.com/steveaoki",
    ],
    priority: "high",
  },
  {
    name: "Hardwell",
    genre: "Big Room",
    accent: "#ef233c",
    homeCity: "Breda, The Netherlands",
    youtube: { handle: "@hardwell", status: "ok" },
    soundcloud: {
      permalink: "hardwell",
      userId: 296190,
      status: "ok",
    },
    website: "https://djhardwell.com/",
    socials: [
      "https://www.youtube.com/@hardwell",
      "https://soundcloud.com/hardwell",
    ],
    priority: "high",
  },
  {
    name: "Carl Cox",
    genre: "Techno",
    accent: "#212529",
    homeCity: "UK",
    youtube: { handle: "@CarlCoxofficialTV", status: "ok" },
    soundcloud: {
      permalink: "carl-cox",
      userId: 13245797,
      status: "ok",
    },
    website: "https://www.carlcox.com/",
    socials: [
      "https://www.youtube.com/@CarlCoxofficialTV",
      "https://soundcloud.com/carl-cox",
      "https://instagram.com/carlcoxofficial",
      "https://facebook.com/carlcox247",
      "https://linktr.ee/carlcoxofficial",
    ],
    priority: "high",
  },
  {
    name: "Eric Prydz",
    genre: "Progressive House",
    accent: "#7209b7",
    homeCity: "Sweden",
    youtube: { handle: "@ericprydz", status: "ok" },
    soundcloud: {
      permalink: "eric-prydz",
      userId: 1038649,
      status: "ok",
    },
    website: "https://www.ericprydz.com/",
    socials: [
      "https://www.youtube.com/@ericprydz",
      "https://soundcloud.com/eric-prydz",
    ],
    priority: "high",
  },
  {
    name: "Amelie Lens",
    genre: "Techno",
    accent: "#d00000",
    homeCity: "Belgium",
    youtube: { handle: "@AmelieLens", status: "ok" },
    soundcloud: {
      permalink: "amelielens",
      userId: 86158258,
      status: "ok",
    },
    website: "https://www.amelielens.com/",
    socials: [
      "https://www.youtube.com/@AmelieLens",
      "https://soundcloud.com/amelielens",
      "https://instagram.com/amelie_lens",
      "https://x.com/AmelieLENS",
      "https://facebook.com/amelielensmusic",
      "https://linktr.ee/amelie.lens",
    ],
    priority: "high",
  },
  {
    name: "Paul van Dyk",
    genre: "Trance",
    accent: "#00b4d8",
    homeCity: "Germany",
    youtube: { handle: "@PaulvanDyk", status: "ok" },
    soundcloud: {
      permalink: "paulvandykofficial",
      userId: 322386,
      status: "ok",
    },
    website: "https://www.paulvandyk.com/",
    socials: [
      "https://www.youtube.com/@PaulvanDyk",
      "https://soundcloud.com/paulvandykofficial",
    ],
    priority: "high",
  },
  {
    name: "Korolova",
    genre: "Melodic Techno",
    accent: "#f72585",
    homeCity: "Ukraine",
    youtube: { handle: "@KOROLOVADJ", status: "ok" },
    soundcloud: {
      permalink: "korolovadj",
      userId: 264150016,
      status: "ok",
    },
    website: "https://solo.to/korolova.dj",
    socials: [
      "https://www.youtube.com/@KOROLOVADJ",
      "https://soundcloud.com/korolovadj",
      "https://www.instagram.com/korolova.dj/",
      "https://solo.to/korolova.dj",
      "https://open.spotify.com/artist/0I6oCyQQ1Q50q97y9B9gAx",
    ],
    priority: "high",
  },
  {
    name: "Kölsch",
    genre: "Melodic Techno",
    accent: "#ffd60a",
    homeCity: "Denmark",
    youtube: { handle: "@KolschOfficial", status: "ok" },
    soundcloud: {
      permalink: "kolsch",
      userId: 4417549,
      status: "ok",
    },
    website: "https://www.kolschofficial.com/",
    socials: [
      "https://www.youtube.com/@KolschOfficial",
      "https://soundcloud.com/kolsch",
    ],
    priority: "high",
  },
  {
    name: "Miss Monique",
    genre: "Melodic Techno",
    accent: "#9b5de5",
    homeCity: "Ukraine",
    youtube: { handle: "@djmissmonique", status: "ok" },
    soundcloud: {
      permalink: "alesia-arkusha",
      userId: 17716472,
      status: "ok",
    },
    website: "https://missmoniquemusic.com/",
    socials: [
      "https://www.youtube.com/@djmissmonique",
      "https://soundcloud.com/alesia-arkusha",
      "https://instagram.com/djmissmonique",
      "https://twitter.com/djmissmonique",
      "https://facebook.com/MissMoniqueUA",
    ],
    priority: "high",
  },
  {
    name: "Ferry Corsten",
    genre: "Trance",
    accent: "#48cae4",
    youtube: { handle: "@FerryCorsten", status: "ok" },
    soundcloud: {
      permalink: "ferry-corsten",
      userId: 3787492,
      status: "ok",
    },
    website: "https://www.ferrycorsten.com/",
    socials: [
      "https://www.youtube.com/@FerryCorsten",
      "https://soundcloud.com/ferry-corsten",
    ],
    priority: "high",
  },
  {
    name: "Topic",
    genre: "Dance",
    accent: "#fb8500",
    homeCity: "Germany",
    youtube: { handle: "@topicmusictv", status: "ok" },
    soundcloud: {
      permalink: "topicmusic",
      userId: 113671916,
      status: "ok",
    },
    website: "https://www.topic-music.com/",
    socials: [
      "https://www.youtube.com/@topicmusictv",
      "https://soundcloud.com/topicmusic",
    ],
    priority: "high",
  },
  {
    name: "Swedish House Mafia",
    genre: "House",
    accent: "#212529",
    youtube: { handle: "@swedishhousemafia", status: "ok" },
    soundcloud: {
      permalink: "officialswedishhousemafia",
      userId: 1181568,
      status: "ok",
    },
    website: "https://swedishhousemafia.com",
    socials: [
      "https://www.youtube.com/@swedishhousemafia",
      "https://soundcloud.com/officialswedishhousemafia",
      "https://instagram.com/swedishhousemafia",
      "https://twitter.com/swedishousemfia",
      "https://tiktok.com/@swedishhousemafia",
      "https://facebook.com/swedishhousemafia",
      "https://swedishhousemafia.komi.io",
    ],
    priority: "high",
  },
  {
    name: "Joel Corry",
    genre: "House",
    accent: "#4cc9f0",
    homeCity: "United Kingdom",
    youtube: { handle: "@JoelCorry", status: "ok" },
    soundcloud: {
      permalink: "joelcorry",
      userId: 15126749,
      status: "ok",
    },
    website: "https://joelcorry.com",
    socials: [
      "https://www.youtube.com/@JoelCorry",
      "https://soundcloud.com/joelcorry",
      "https://instagram.com/joelcorry",
      "https://twitter.com/JoelCorry",
      "https://tiktok.com/@joelcorry",
      "https://facebook.com/JoelCorry",
    ],
    priority: "high",
  },
  {
    name: "Alok",
    genre: "House",
    accent: "#ff6b35",
    homeCity: "Brazil",
    youtube: { handle: "UCQlaArsZfebRbb70iXm6usg", status: "ok" },
    soundcloud: { permalink: "livealok", userId: 2737750, status: "ok" },
    website: "https://alokmusic.com/",
    priority: "high",
  },
  {
    name: "Afrojack",
    genre: "House",
    accent: "#ffd60a",
    homeCity: "Netherlands",
    youtube: { handle: "@afrojack", status: "ok" },
    soundcloud: { permalink: "afrojack", userId: 26253177, status: "ok" },
    website: "https://www.afrojack.com/",
    priority: "high",
  },
  {
    name: "Anyma",
    genre: "Melodic Techno",
    accent: "#7b2cbf",
    youtube: { handle: "@anyma_ofc", status: "ok" },
    soundcloud: { permalink: "anyma_ofc", userId: 751071589, status: "ok" },
    website: "https://www.anyma.com/",
    priority: "high",
  },
  {
    name: "Peggy Gou",
    genre: "House",
    accent: "#e63946",
    youtube: { handle: "UCWd5yMFDEuSCWzTM4xuA1fg", status: "ok" },
    soundcloud: { permalink: "peggygou", userId: 14912916, status: "ok" },
    website: "https://www.peggygou.com/",
    priority: "high",
  },
  {
    name: "Calvin Harris",
    genre: "Dance",
    accent: "#ff9f1c",
    homeCity: "Scotland, UK",
    youtube: { handle: "@CalvinHarris", status: "ok" },
    soundcloud: { permalink: "calvinharris", userId: 208934, status: "ok" },
    website: "https://calvinharris.com/",
    priority: "high",
  },
  {
    name: "Tiësto",
    genre: "Big Room",
    accent: "#00bbf9",
    homeCity: "Netherlands",
    youtube: { handle: "@tiesto", status: "ok" },
    soundcloud: { permalink: "tiesto", userId: 141707, status: "ok" },
    website: "https://www.tiesto.com/",
    priority: "high",
  },
  {
    name: "Reinier Zonneveld",
    genre: "Techno",
    accent: "#ff006e",
    youtube: {
      handle: "@ReinierZonneveld_FilthOnAcid",
      status: "ok",
    },
    soundcloud: {
      permalink: "reinier-zonneveld",
      userId: 367568,
      status: "ok",
    },
    priority: "high",
  },
  {
    name: "Alan Walker",
    genre: "EDM",
    accent: "#56cfe1",
    youtube: { handle: "@Alanwalkermusic", status: "ok" },
    soundcloud: { permalink: "alanwalker", userId: 18693253, status: "ok" },
    priority: "high",
  },
  {
    name: "Jamie Jones",
    genre: "Tech House",
    accent: "#f72585",
    youtube: { handle: "@JamieJonesOfficial", status: "ok" },
    soundcloud: { permalink: "jamie-jones", userId: 1283623, status: "ok" },
    website: "https://jamiejones.com/",
    priority: "high",
  },
  {
    name: "R3hab",
    genre: "Big Room",
    accent: "#ffbe0b",
    youtube: { handle: "@r3hab", status: "ok" },
    soundcloud: { permalink: "r3hab", userId: 351064, status: "ok" },
    priority: "high",
  },
  {
    name: "Claptone",
    genre: "Deep House",
    accent: "#ffd60a",
    youtube: { handle: "@CLAPTONEOFFICIAL", status: "ok" },
    soundcloud: { permalink: "claptone", userId: 4452531, status: "ok" },
    priority: "high",
  },
  {
    name: "Skrillex",
    genre: "Bass",
    accent: "#80ffdb",
    youtube: { handle: "@skrillex", status: "ok" },
    soundcloud: { permalink: "skrillex", userId: 856062, status: "ok" },
    priority: "high",
  },
  {
    name: "Vini Vici",
    genre: "Psytrance",
    accent: "#9b5de5",
    youtube: { handle: "@ViniViciMusic", status: "ok" },
    soundcloud: {
      permalink: "vinivicimusic",
      userId: 57637947,
      status: "ok",
    },
    priority: "high",
  },
  {
    name: "W&W",
    genre: "Big Room",
    accent: "#00b4d8",
    homeCity: "Netherlands",
    youtube: { handle: "@wandwmusic", status: "ok" },
    soundcloud: { permalink: "wandw", userId: 630356, status: "ok" },
    website: "https://www.wandwmusic.com/",
    priority: "high",
  },
  {
    name: "Timmy Trumpet",
    genre: "Big Room",
    accent: "#ffba08",
    homeCity: "Australia",
    youtube: {
      handle: "UCd61k-5ykv_4RIbQg-Mpvrg",
      status: "ok",
    },
    soundcloud: { permalink: "timmytrumpet", userId: 574349, status: "ok" },
    website: "https://www.timmytrumpet.com/",
    priority: "high",
  },
  {
    name: "Indira Paganotto",
    genre: "Hard Techno",
    accent: "#ff006e",
    youtube: { handle: "@IndiraPaganotto", status: "ok" },
    soundcloud: {
      permalink: "indirapaganotto",
      userId: 682788,
      status: "ok",
    },
    website: "https://indirapaganotto.com/",
    priority: "high",
  },
  {
    name: "The Martinez Brothers",
    genre: "House",
    accent: "#f4a261",
    youtube: { handle: "@TheMartinezBrosTV", status: "ok" },
    soundcloud: { permalink: "themartinezbros", status: "ok" },
    website: "https://themartinezbrothers.com/",
    priority: "high",
  },
  {
    name: "Zedd",
    genre: "Electro House",
    accent: "#4cc9f0",
    youtube: { handle: "UCPNokRZ9hacjIQ3IQL6HNUQ", status: "ok" },
    soundcloud: { permalink: "zedd", userId: 462658, status: "ok" },
    priority: "high",
  },
  // Operator Top 100 batch #45–#89 (validated handles only).
  {
    name: "Bassjackers",
    genre: "Big Room",
    accent: "#e63946",
    youtube: { handle: "@Bassjackers", status: "ok" },
    soundcloud: { permalink: "bassjackers", status: "ok" },
    priority: "high",
  },
  {
    name: "Quintino",
    genre: "Big Room",
    accent: "#ff9f1c",
    homeCity: "Netherlands",
    youtube: { handle: "@Quintino", status: "ok" },
    soundcloud: { permalink: "quintino", status: "ok" },
    priority: "high",
  },
  {
    name: "Boris Brejcha",
    genre: "Techno",
    accent: "#ff006e",
    youtube: { handle: "UCukezONa4veoJBeK9UuVZew", status: "ok" },
    soundcloud: { permalink: "boris-brejcha", status: "ok" },
    priority: "high",
  },
  {
    name: "HUGEL",
    genre: "Melodic House",
    accent: "#06d6a0",
    youtube: { handle: "@HUGELBeats", status: "ok" },
    soundcloud: { permalink: "hugelmusic", status: "ok" },
    priority: "high",
  },
  {
    name: "Nora En Pure",
    genre: "Deep House",
    accent: "#48cae4",
    youtube: { handle: "@noraenpure", status: "ok" },
    soundcloud: { permalink: "noraenpure", status: "ok" },
    priority: "high",
  },
  {
    name: "ATB",
    genre: "Trance",
    accent: "#0077b6",
    youtube: { handle: "@atb", status: "ok" },
    soundcloud: {
      permalink: "atb-music",
      userId: 190764251,
      status: "ok",
    },
    website: "https://atb-music.com",
    socials: [
      "https://www.youtube.com/@atb",
      "https://soundcloud.com/atb-music",
      "https://instagram.com/atbandre",
      "https://twitter.com/atbandre",
      "https://tiktok.com/@atbandre",
    ],
    priority: "high",
  },
  {
    name: "Deborah De Luca",
    genre: "Techno",
    accent: "#c9184a",
    youtube: { handle: "@DeborahDeLucaOfficial", status: "ok" },
    soundcloud: { permalink: "deborahdeluca", status: "ok" },
    website: "https://deborahdeluca.it/",
    priority: "high",
  },
  {
    name: "Above & Beyond",
    genre: "Trance",
    accent: "#7209b7",
    youtube: { handle: "@aboveandbeyond", status: "ok" },
    soundcloud: { permalink: "aboveandbeyond", status: "ok" },
    priority: "high",
  },
  {
    name: "Nervo",
    genre: "Progressive House",
    accent: "#f72585",
    youtube: { handle: "@NERVO", status: "ok" },
    soundcloud: { permalink: "nervomusic", status: "ok" },
    priority: "high",
  },
  {
    name: "Sub Zero Project",
    genre: "Hard House",
    accent: "#3a0ca3",
    youtube: { handle: "@SubZeroProject", status: "ok" },
    soundcloud: { permalink: "subzeroproject", status: "ok" },
    priority: "high",
  },
  {
    name: "Lucas & Steve",
    genre: "Future House",
    accent: "#ffb703",
    youtube: { handle: "UCIAzXmeDqLu-HY9yJ5Rd4pg", status: "ok" },
    soundcloud: { permalink: "lucasandsteve", status: "ok" },
    priority: "high",
  },
  {
    name: "Nico Moreno",
    genre: "Hard Techno",
    accent: "#d00000",
    youtube: { handle: "@nicomoreno_music", status: "ok" },
    soundcloud: {
      permalink: "nicomorenomusic",
      userId: 24188511,
      status: "ok",
      note: "not bare nicomoreno (different account)",
    },
    website: "https://nicomoreno.komi.io/",
    socials: [
      "https://www.youtube.com/@nicomoreno_music",
      "https://soundcloud.com/nicomorenomusic",
      "https://instagram.com/nicomorenomusic",
      "https://tiktok.com/@nicomoreno_music",
      "https://facebook.com/nicomorenomusic",
    ],
    priority: "high",
  },
  {
    name: "GORDO",
    genre: "Tech House",
    accent: "#fb8500",
    youtube: { handle: "@gordoszn", status: "ok" },
    soundcloud: {
      permalink: "gordoszn",
      userId: 956458,
      status: "ok",
    },
    website: "https://www.gordoszn.com/",
    socials: [
      "https://www.youtube.com/@gordoszn",
      "https://soundcloud.com/gordoszn",
      "https://instagram.com/gordoszn",
      "https://twitter.com/gordoszn",
      "https://facebook.com/gordoszn",
    ],
    priority: "high",
  },
  {
    name: "The Chainsmokers",
    genre: "Future Bass",
    accent: "#4cc9f0",
    youtube: { handle: "@thechainsmokers", status: "ok" },
    soundcloud: { permalink: "thechainsmokers", status: "ok" },
    priority: "high",
  },
  {
    name: "Liu",
    genre: "Bass House",
    accent: "#2a9d8f",
    homeCity: "Brazil",
    // Official channel is @Liumusic (UCQlaArsZfebRbb70iXm6usg).
    // @liulive / @LiuLive is a different account (Людмила Колесникова).
    youtube: { handle: "@Liumusic", status: "ok" },
    soundcloud: { permalink: "liulive", status: "ok" },
    socials: [
      "https://instagram.com/liulive",
      "https://twitter.com/liulive",
      "https://facebook.com/liulive",
    ],
    priority: "high",
  },
  {
    name: "Mike Williams",
    genre: "Future House",
    accent: "#e9c46a",
    youtube: { handle: "@mikewilliams", status: "ok" },
    soundcloud: { permalink: "mikewilliams", status: "ok" },
    priority: "high",
  },
  {
    name: "KAAZE",
    genre: "Progressive House",
    accent: "#9b5de5",
    youtube: { handle: "@KAAZEOfficial", status: "ok" },
    soundcloud: { permalink: "kaaze", status: "ok" },
    priority: "high",
  },
  {
    name: "Burak Yeter",
    genre: "Deep House",
    accent: "#e76f51",
    youtube: { handle: "UCkCbJ6kruvug_6XOusB1rdQ", status: "ok" },
    soundcloud: { permalink: "burakyeter", status: "ok" },
    priority: "high",
  },
  {
    name: "Le Twins",
    genre: "Melodic Techno",
    accent: "#8338ec",
    youtube: { handle: "@letwinsdjs", status: "ok" },
    soundcloud: {
      permalink: "le-twins-52553281",
      userId: 180422861,
      status: "ok",
    },
    socials: [
      "https://www.youtube.com/@letwinsdjs",
      "https://soundcloud.com/le-twins-52553281",
      "https://instagram.com/officialletwins",
      "https://facebook.com/officialletwins",
      "https://twitter.com/Letwinsofficial",
    ],
    priority: "high",
  },
  {
    name: "I Hate Models",
    genre: "Techno",
    accent: "#212529",
    youtube: { handle: "@ihatemodels", status: "ok" },
    soundcloud: { permalink: "ihatemodels", status: "ok" },
    priority: "high",
  },
  {
    name: "Marnik",
    genre: "Big Room",
    accent: "#ff006e",
    youtube: { handle: "@marnikofficial", status: "ok" },
    soundcloud: { permalink: "marnikofficial", status: "ok" },
    priority: "high",
  },
  {
    name: "Chris Stussy",
    genre: "Tech House",
    accent: "#118ab2",
    youtube: { handle: "@chrisstussy", status: "ok" },
    soundcloud: { permalink: "chrisstussy", status: "ok" },
    priority: "high",
  },
  {
    name: "deadmau5",
    genre: "Progressive House",
    accent: "#00f5d4",
    youtube: { handle: "@deadmau5", status: "ok" },
    soundcloud: { permalink: "deadmau5", status: "ok" },
    priority: "high",
  },
  {
    name: "WUKONG",
    genre: "Melodic Techno",
    accent: "#ffd60a",
    youtube: { handle: "@WUKONGofficial", status: "ok" },
    soundcloud: { permalink: "wukongofficial", status: "ok" },
    priority: "high",
  },
  {
    name: "Fedde Le Grand",
    genre: "Electro House",
    accent: "#ef476f",
    youtube: { handle: "@FeddeLeGrand", status: "ok" },
    soundcloud: { permalink: "feddelegrand", status: "ok" },
    priority: "high",
  },
  {
    name: "Plastik Funk",
    genre: "House",
    accent: "#06d6a0",
    youtube: { handle: "@plastikfunk", status: "ok" },
    soundcloud: { permalink: "plastikfunk", status: "ok" },
    priority: "high",
  },
  {
    name: "DubVision",
    genre: "Progressive House",
    accent: "#4361ee",
    youtube: { handle: "@DubVision", status: "ok" },
    soundcloud: { permalink: "dubvision", status: "ok" },
    socials: [
      "https://www.youtube.com/@DubVision",
      "https://soundcloud.com/dubvision",
      "https://www.instagram.com/dubvisionmusic/",
      "https://x.com/dubvisionmusic",
      "https://linktr.ee/dubvision",
      "https://www.instagram.com/halo__ofc/",
      "https://x.com/Halo__ofc",
    ],
    priority: "high",
  },
  {
    name: "B Jones",
    genre: "Tech House",
    accent: "#f77f00",
    youtube: { handle: "@bjonesdj", status: "ok" },
    soundcloud: { permalink: "bjonesdj", status: "ok" },
    priority: "high",
  },
  {
    name: "Giuseppe Ottaviani",
    genre: "Trance",
    accent: "#7b2cbf",
    youtube: { handle: "UCdY9Y8zBYz-jHIs8DDxbd4Q", status: "ok" },
    soundcloud: { permalink: "GIUSEPPEOTTAVIANI", status: "ok" },
    priority: "high",
  },
  {
    name: "Marshmello",
    genre: "Future Bass",
    accent: "#e9ecef",
    youtube: { handle: "UCEdvpU2pFRCVqU6yIPyTpMQ", status: "ok" },
    soundcloud: { permalink: "marshmellomusic", status: "ok" },
    priority: "high",
  },
  // Handle-gap batch — verified profiles only (see djSocialPins comments).
  {
    name: "KSHMR",
    genre: "Big Room",
    accent: "#e63946",
    youtube: { handle: "UCFMjkrMT7Gvg84v0av-DIwA", status: "ok" },
    soundcloud: { permalink: "kshmr", status: "ok" },
    priority: "high",
  },
  {
    name: "Nicky Romero",
    genre: "Progressive House",
    accent: "#ffbe0b",
    youtube: { handle: "https://www.youtube.com/user/nickyromerotv", status: "ok" },
    soundcloud: { permalink: "nickyromero", status: "ok" },
    website: "https://nickyromero.com/",
    priority: "high",
  },
  {
    name: "DJ Snake",
    genre: "Bass",
    accent: "#80ffdb",
    youtube: { handle: "@DJSnake", status: "ok" },
    soundcloud: {
      permalink: "djsnake",
      userId: 670089,
      status: "ok",
      note: "not on.soundcloud shortlink (404)",
    },
    website: "https://djsnake.com/",
    socials: [
      "https://www.youtube.com/@DJSnake",
      "https://soundcloud.com/djsnake",
      "https://instagram.com/djsnake",
      "https://twitter.com/djsnake",
      "https://tiktok.com/@djsnake",
      "https://linktr.ee/djsnake",
    ],
    priority: "high",
  },
  {
    name: "Michael Bibi",
    genre: "Tech House",
    accent: "#ff006e",
    youtube: { handle: "@michaelbibi", status: "ok" },
    soundcloud: { permalink: "bibi-87", status: "ok" },
    priority: "high",
  },
  {
    name: "Alesso",
    genre: "Progressive House",
    accent: "#4cc9f0",
    youtube: { handle: "@alesso", status: "ok" },
    soundcloud: { permalink: "alesso", status: "ok" },
    priority: "high",
  },
  {
    name: "Mochakk",
    genre: "Tech House",
    accent: "#f4a261",
    youtube: { handle: "@mochakk", status: "ok" },
    soundcloud: { permalink: "mochakkmusic", status: "ok" },
    priority: "high",
  },
  {
    name: "Cuebrick",
    genre: "Big Room",
    accent: "#8338ec",
    youtube: { handle: "@cuebrick", status: "ok" },
    soundcloud: { permalink: "cuebrick", status: "ok" },
    priority: "high",
  },
  {
    name: "Mariana Bo",
    genre: "Hardstyle",
    accent: "#e63946",
    youtube: { handle: "@marianabo", status: "ok" },
    soundcloud: {
      permalink: "borrego-s",
      userId: 3610757,
      status: "ok",
    },
    socials: [
      "https://www.youtube.com/@marianabo",
      "https://soundcloud.com/borrego-s",
      "https://www.instagram.com/djmarianabo/",
      "https://x.com/djmarianabo",
    ],
    priority: "high",
  },
  {
    name: "Fantasm",
    genre: "Hard Techno",
    accent: "#d00000",
    youtube: { handle: "@fantasm_techno", status: "ok" },
    soundcloud: {
      permalink: "kenzo-meservey",
      userId: 696498012,
      status: "ok",
    },
    priority: "high",
  },
  {
    name: "VINAI",
    genre: "Big Room",
    accent: "#ff006e",
    youtube: { handle: "@vinaiofficial", status: "ok" },
    soundcloud: { permalink: "wearevinai", status: "ok" },
    priority: "high",
  },
  {
    name: "Faustix",
    genre: "Future House",
    accent: "#ffba08",
    youtube: { handle: "@faustixmusic", status: "ok" },
    soundcloud: { permalink: "faustix", status: "ok" },
    priority: "high",
  },
  {
    name: "Honey Dijon",
    genre: "House",
    accent: "#f72585",
    youtube: { handle: "@honeydijon", status: "ok" },
    soundcloud: { permalink: "honeydijon", status: "ok" },
    priority: "high",
  },
  {
    name: "Nils van Zandt",
    genre: "Big Room",
    accent: "#00b4d8",
    youtube: { handle: "@nilsvanzandt", status: "ok" },
    soundcloud: { permalink: "nilsvanzandtofficial", status: "ok" },
    priority: "high",
  },
  {
    name: "Marlon Hoffstadt",
    genre: "Trance",
    accent: "#ff9f1c",
    youtube: { handle: "@marlonhoffstadt", status: "ok" },
    soundcloud: { permalink: "marlonhoffstadt", status: "ok" },
    priority: "high",
  },
  {
    name: "1788-L",
    genre: "Riddim",
    accent: "#c1121f",
    homeCity: "United States",
    youtube: { handle: "@1788L", status: "ok" },
    website: "https://1788-l.com",
    socials: [
      "https://www.youtube.com/@1788L",
      "https://instagram.com/1788_l",
      "https://twitter.com/l_1788",
      "https://open.spotify.com/artist/7oB4pCSzvvRtZka6DxXUfN",
    ],
    priority: "normal",
  },
  {
    name: "NEGITIV",
    genre: "Hard Techno",
    accent: "#7b2cbf",
    homeCity: "Cologne, DE",
    youtube: { handle: "@negitivofficial", status: "ok" },
    soundcloud: { permalink: "negitivofficial", status: "ok" },
    website: "https://negitiv.com",
    socials: [
      "https://www.youtube.com/@negitivofficial",
      "https://soundcloud.com/negitivofficial",
      "https://www.instagram.com/negitiv/",
      "https://linktr.ee/negitiv",
      "https://www.bcbfamily.com/artists/negitiv",
      "https://www.tiktok.com/@negitivv",
    ],
    priority: "normal",
  },
  {
    name: "MANDY",
    genre: "Hard Dance",
    accent: "#ff006e",
    homeCity: "Belgium",
    youtube: { handle: "@mandyofficialbe", status: "ok" },
    website: "https://www.youtube.com/@mandyofficialbe",
    socials: [
      "https://www.youtube.com/@mandyofficialbe",
      "https://www.instagram.com/mandyofficial_be/",
      "https://x.com/djmandyofficial",
      "https://www.facebook.com/MANDYofficial",
    ],
    priority: "normal",
  },
  {
    name: "Steve Angello",
    genre: "Progressive House",
    accent: "#e63946",
    homeCity: "Stockholm, SE",
    youtube: { handle: "@steveangello", status: "ok" },
    soundcloud: { permalink: "steveangello", status: "ok" },
    website: "https://www.steveangello.com/",
    socials: [
      "https://www.youtube.com/steveangello",
      "https://soundcloud.com/steveangello",
      "https://www.instagram.com/steveangello/",
      "https://x.com/SteveAngello",
      "https://www.facebook.com/steveangello",
      "https://www.tiktok.com/@steveangello",
      "https://open.spotify.com/artist/4FqPRilb0Ja0TKG3RS3y4s",
    ],
    priority: "high",
  },
];

/**
 * Effective deep-scan roster = curated + graduated discovery candidates.
 */
export const ARTIST_ROSTER: ArtistRosterEntry[] = [
  ...ARTIST_ROSTER_CURATED,
  ...loadRosterGraduates(),
];

export function rosterMissingHandles(): ArtistRosterEntry[] {
  return ARTIST_ROSTER.filter((a) => {
    const yt = a.youtube?.status;
    const sc = a.soundcloud?.status;
    return (
      yt === "missing" ||
      yt === "weak" ||
      yt === "unverified" ||
      sc === "missing" ||
      sc === "weak" ||
      sc === "unverified" ||
      !a.youtube?.handle ||
      !a.soundcloud?.permalink
    );
  });
}

/** Curated genre for a DJ name/slug, when the roster knows them. */
export function rosterGenreForArtist(
  nameOrSlug: string | null | undefined,
): CanonicalGenre | null {
  if (!nameOrSlug?.trim()) return null;
  const key = slugify(nameOrSlug);
  for (const a of ARTIST_ROSTER) {
    if (slugify(a.name) === key) return normalizeGenre(a.genre);
  }
  return null;
}
